import { generateDocs } from "./targets/docs.js";
import { generateVanilla } from "./targets/vanilla.js";
import { generateVue, type VueConversionOptions } from "./targets/vue.js";
import { VUE_HOST_PATH, vueHostModule } from "./targets/vue-host.js";
import { VUE_HTML_PATH, vueHtmlModule } from "./targets/vue-html.js";
import { VUE_CONTROL_PATH, vueControlModule } from "./targets/vue-control.js";
import { VUE_PROPS_PATH, vuePropsModule } from "./targets/vue-props.js";
import { HtmlDiagnosticError } from "./diagnostics.js";
import type { ComponentDefinition } from "./template.js";
import { compileComponentStylesForBuild } from "./component-styles-build.js";

export const GENERATOR_VERSION = "1.0.0-alpha.15";

export interface GeneratedArtifact {
  readonly path: string;
  readonly content: string;
}

export interface GenerationOptions {
  /** A closed component graph proves no descendant reads this definition's state through <context>. */
  readonly noContextReaders?: boolean;
}

export function generateComponent(
  definition: ComponentDefinition,
  options?: GenerationOptions,
): readonly GeneratedArtifact[] {
  const vanilla = generateVanilla(definition, GENERATOR_VERSION, options?.noContextReaders === true);
  const vue = convertedToVue(definition);
  const docs = generateDocs(definition, GENERATOR_VERSION);
  const { name, tag } = definition.contract;

  return Object.freeze([
    Object.freeze({ path: `vanilla/${name}.js`, content: vanilla.module }),
    Object.freeze({ path: `vanilla/${name}.d.ts`, content: vanilla.declaration }),
    ...(vue === undefined ? [] : [Object.freeze({ path: `vue/${name}.vue`, content: vue })]),
    Object.freeze({
      path: `styles/${tag}.css`,
      content: `/* Generated by HTML Next ${GENERATOR_VERSION}. Do not edit. */\n${compileComponentStylesForBuild(definition.css, definition).css}${definition.css === "" ? "" : "\n"}`,
    }),
    Object.freeze({ path: `docs/${tag}.md`, content: docs }),
  ]);
}

/** The one module the converted Vue components share; every package that emits Vue ships it once. */
export function vueHostArtifact(): GeneratedArtifact {
  return Object.freeze({ path: VUE_HOST_PATH, content: vueHostModule(GENERATOR_VERSION) });
}

/** Feature-specific safe-markup helper for Vue components that author `$html`. */
export function vueHtmlArtifact(): GeneratedArtifact {
  return Object.freeze({ path: VUE_HTML_PATH, content: vueHtmlModule(GENERATOR_VERSION) });
}

/** Feature-specific native-control binding and hydration preservation for Vue. */
export function vueControlArtifact(): GeneratedArtifact {
  return Object.freeze({ path: VUE_CONTROL_PATH, content: vueControlModule(GENERATOR_VERSION) });
}

/** Feature-specific typed-prop boundary for Vue components that declare props. */
export function vuePropsArtifact(): GeneratedArtifact {
  return Object.freeze({ path: VUE_PROPS_PATH, content: vuePropsModule(GENERATOR_VERSION) });
}

export { importsVueHost } from "./targets/vue-host.js";
export { importsVueHtml } from "./targets/vue-html.js";
export { importsVueControl } from "./targets/vue-control.js";
export { importsVueProps } from "./targets/vue-props.js";

export type { ComponentDefinition } from "./template.js";

/**
 * The Vue conversion, or nothing when the definition uses a construct Vue conversion does not map
 * yet. HTML Next's own outputs do not depend on it; `generateVueComponent` reports the reason.
 */
function convertedToVue(definition: ComponentDefinition): string | undefined {
  try {
    return generateVue(definition, GENERATOR_VERSION);
  } catch (error) {
    if (error instanceof HtmlDiagnosticError && /^HT03\d$/.test(error.diagnostic.code)) return undefined;
    throw error;
  }
}

/** Converts one definition to a Vue single-file component, failing with a diagnostic if it cannot. */
export function generateVueComponent(definition: ComponentDefinition, options?: VueConversionOptions): string {
  return generateVue(definition, GENERATOR_VERSION, options);
}
