import { generateDocs } from "./targets/docs.js";
import { generateVanilla } from "./targets/vanilla.js";
import { generateVue } from "./targets/vue.js";
import { VUE_HOST_PATH, vueHostModule } from "./targets/vue-host.js";
import { HtmlDiagnosticError } from "./diagnostics.js";
import type { ComponentDefinition } from "./template.js";
import { compileComponentStylesForBuild } from "./component-styles-build.js";

export const GENERATOR_VERSION = "1.0.0-alpha.6";

export interface GeneratedArtifact {
  readonly path: string;
  readonly content: string;
}

export function generateComponent(
  definition: ComponentDefinition,
): readonly GeneratedArtifact[] {
  const vanilla = generateVanilla(definition, GENERATOR_VERSION);
  const vue = convertedToVue(definition);
  const docs = generateDocs(definition, GENERATOR_VERSION);
  const { name, tag } = definition.contract;

  return Object.freeze([
    Object.freeze({ path: `vanilla/${name}.js`, content: vanilla.module }),
    Object.freeze({ path: `vanilla/${name}.d.ts`, content: vanilla.declaration }),
    ...(vue === undefined ? [] : [Object.freeze({ path: `vue/${name}.vue`, content: vue })]),
    Object.freeze({
      path: `styles/${tag}.css`,
      content: `/* Generated by HTML Next ${GENERATOR_VERSION}. Do not edit. */\n${compileComponentStylesForBuild(definition.css, definition).css}${definition.css === "" ? "" : "\n"}`,
    }),
    Object.freeze({ path: `docs/${tag}.md`, content: docs }),
  ]);
}

/** The one module the converted Vue components share; every package that emits Vue ships it once. */
export function vueHostArtifact(): GeneratedArtifact {
  return Object.freeze({ path: VUE_HOST_PATH, content: vueHostModule(GENERATOR_VERSION) });
}

export { importsVueHost } from "./targets/vue-host.js";

export type { ComponentDefinition } from "./template.js";

/**
 * The Vue conversion, or nothing when the definition uses a construct Vue conversion does not map
 * yet. HTML Next's own outputs do not depend on it; `generateVueComponent` reports the reason.
 */
function convertedToVue(definition: ComponentDefinition): string | undefined {
  try {
    return generateVue(definition, GENERATOR_VERSION);
  } catch (error) {
    if (error instanceof HtmlDiagnosticError && /^HT03\d$/.test(error.diagnostic.code)) return undefined;
    throw error;
  }
}

/** Converts one definition to a Vue single-file component, failing with a diagnostic if it cannot. */
export function generateVueComponent(definition: ComponentDefinition): string {
  return generateVue(definition, GENERATOR_VERSION);
}
