import type { ComponentDefinition } from "../template.js";
import type { PropContract, PropType } from "../types.js";
import { declarationTypeNode, formatType } from "../type-system.js";
import { targetComponent } from "./backend.js";

function typeSource(type: PropType): string {
  return `\`${formatType(type).replaceAll("|", "\\|")}\``;
}

function defaultSource(prop: PropContract): string {
  return "default" in prop ? `\`${JSON.stringify(prop.default)}\`` : "—";
}

function targetSource(prop: PropContract): string {
  return "attribute" in prop.target
    ? `attribute \`${prop.target.attribute}\``
    : `property \`${prop.target.property}\``;
}

function cell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll(/\s+/g, " ").trim();
}

export function generateDocs(definition: ComponentDefinition, version: string): string {
  const { contract } = definition;
  const target = targetComponent(definition);
  const props = Object.entries(contract.props);
  const rows = props.length === 0
    ? ["| — | — | — | — | — | — | This component has no declared props. |"]
    : props.map(([name, prop]) => {
      const type = prop.select === undefined ? typeSource(prop.type)
        : prop.select.options.map((option) => `\`${prop.select!.from}=${String(option.value)}\` → ${typeSource(option.type)}`).join("; ");
      const values = prop.values === undefined ? "—" : prop.values.map((value) => `\`${String(value)}\``).join(", ");
      return `| \`${name}\` | ${type} | ${values} | ${prop.required ? "yes" : "no"} | ${defaultSource(prop)} | ${targetSource(prop)} | ${cell(prop.description)} |`;
    });

  return [
    `<!-- Generated by HTML Next ${version}. Do not edit. -->`,
    `# ${contract.name}`,
    "",
    ...(contract.status === undefined ? [] : [`> **Status: ${contract.status.toUpperCase()}.** HTML Next early-release component API.`, ""]),
    ...(contract.summary === undefined ? [] : [contract.summary, ""]),
    `- Invocation: \`<${contract.tag}>\``,
    `- Native element: ${(definition.root?.kind === "native" ? definition.root.choices : [contract.nativeElement]).map((name) => `\`<${name}>\``).join(" or ")}`,
    `- Contract schema: \`${contract.version}\``,
    "",
    "## Props",
    "",
    "| Prop | Type | Values | Required | Default | Target | Description |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
    "Native attributes and framework-native event surfaces pass through to the native root. Declared prop targets and template-owned attributes take precedence.",
    "",
    "## Slots",
    "",
    ...(target.slots.length === 0
      ? ["This component has no projected-content slots."]
      : target.slots.map((slot) =>
        `- ${slot.name === undefined ? "Default slot" : `\`${slot.name}\``}: ${slot.required ? "required" : "optional"}${slot.dynamic ? "; selected from data at runtime" : ""}.`
      )),
    "",
    "## Events",
    "",
    ...(target.events.length === 0
      ? ["This component declares no custom events."]
      : [
        "| Event | Detail | Bubbles | Composed | Cancelable |",
        "| --- | --- | --- | --- | --- |",
        ...target.events.map((event) =>
          `| \`${event.name}\` | \`${formatType(declarationTypeNode(event.type, event.shape)!).replaceAll("|", "\\|")}\` | ${event.bubbles ? "yes" : "no"} | ${event.composed ? "yes" : "no"} | ${event.cancelable ? "yes" : "no"} |`
        ),
      ]),
    "",
    "## Usage",
    "",
    "```html",
    `<${contract.tag}>Button label</${contract.tag}>`,
    "```",
    "",
    "```tsx",
    `import { ${contract.name} } from "./react/${contract.name}.js";`,
    "",
    `<${contract.name}>Button label</${contract.name}>`,
    "```",
    "",
    "## Runtime support",
    "",
    `The generated targets use the same HTML Next definition as the live runtime${definition.controller === undefined ? "." : ` and load its declared controller module \`${definition.controller}\`.`} Mutable and computed state, handlers, structural rendering, data, validation, lifecycle, SSR adoption, and projected content therefore follow the shared conformance rules rather than target-specific interpretations.`,
    "",
  ].join("\n");
}
