import type { GeneratedArtifact } from "../generate.js";
import { SAFE_HTML_SANITIZER_SOURCE } from "./shared-generated.js";

/** Feature-specific safe-markup output; generated React does not import the HTML Next runtime. */
export function reactHtmlArtifact(version: string): GeneratedArtifact {
  return Object.freeze({ path: "react/html.ts", content: `// Generated by HTML Next ${version}. Do not edit.
import { createElement, Fragment, type ReactNode } from "react";
import { defaultTreeAdapter, html as parse5Html, parseFragment, type DefaultTreeAdapterTypes } from "parse5";

${SAFE_HTML_SANITIZER_SOURCE}

function browserChildren(parent: ParentNode, projected = false): ReactNode[] {
  return Array.from(parent.childNodes).flatMap((node, index): ReactNode[] => {
    if (node.nodeType === 3) return [node.textContent ?? ""];
    if (node.nodeType !== 1) return [];
    const element = node as Element;
    const attributes = Object.fromEntries(Array.from(element.attributes, ({ name, value }) => [name, value]));
    return [createElement(element.localName, { ...attributes, ...(projected ? { "data-slotted": "" } : {}), key: index }, ...browserChildren(element))];
  });
}

function serverChildren(nodes: readonly DefaultTreeAdapterTypes.ChildNode[], projected = false): ReactNode[] {
  return nodes.flatMap((node, index): ReactNode[] => {
    if (node.nodeName === "#text" && "value" in node) return [node.value];
    if (!("tagName" in node)) return [];
    const attributes = Object.fromEntries(node.attrs.map(({ name, value }) => [name, value]));
    return [createElement(node.tagName, { ...attributes, ...(projected ? { "data-slotted": "" } : {}), key: index }, ...serverChildren(node.childNodes))];
  });
}

function safeNodes(html: string, projected: boolean): ReactNode[] {
  if (typeof document !== "undefined") {
    // Native setHTML() is deliberately not used: Firefox's malformed-table order differs.
    const template = document.createElement("template");
    template.innerHTML = html;
    sanitizeBrowser(template.content);
    return browserChildren(template.content, projected);
  }
  const context = defaultTreeAdapter.createElement("template", HTML_NAMESPACE, []);
  const fragment = parseFragment(context, html, {});
  sanitizeServer(fragment);
  return serverChildren(fragment.childNodes, projected);
}

/** Safe markup as React nodes, with no extra DOM element for inline <template $html>. */
export function SanitizedHtml({ value, projected = false }: { readonly value: string; readonly projected?: boolean }): ReactNode {
  return createElement(Fragment, null, ...safeNodes(value, projected));
}
` });
}
