import type { GeneratedArtifact } from "../generate.js";

const SOURCE = `import React from "react";

const registryKey = Symbol.for("nextwebwg.html-next.react.context.v1");
type ContextValue = { readonly value: unknown } | undefined;
type Registry = Map<string, React.Context<ContextValue>>;
const globalRegistry = globalThis as unknown as Record<symbol, Registry | undefined>;

/** A context identity shared by independently converted component libraries. */
export function componentContext<T>(tag: string, name: string): React.Context<{ readonly value: T } | undefined> {
  let registry = globalRegistry[registryKey];
  if (registry === undefined) {
    registry = new Map();
    globalRegistry[registryKey] = registry;
  }
  const key = tag + "\\u0000" + name;
  let context = registry.get(key);
  if (context === undefined) {
    context = React.createContext<ContextValue>(undefined);
    registry.set(key, context);
  }
  return context as React.Context<{ readonly value: T } | undefined>;
}
`;

export function reactContextArtifact(version: string): GeneratedArtifact {
  return Object.freeze({ path: "react/context.ts", content: `// Generated by HTML Next ${version}. Do not edit.\n${SOURCE}` });
}
