import { SAFE_DEFAULT_ELEMENTS, SAFE_GLOBAL_ATTRIBUTES } from "../sanitizer-default.js";
import type { GeneratedArtifact } from "../generate.js";

/** Feature-specific safe-markup output; generated React does not import the HTML Next runtime. */
export function reactHtmlArtifact(version: string): GeneratedArtifact {
  return Object.freeze({ path: "react/html.ts", content: `// Generated by HTML Next ${version}. Do not edit.
import { createElement, Fragment, type ReactNode } from "react";
import { defaultTreeAdapter, html as parse5Html, parseFragment, type DefaultTreeAdapterTypes } from "parse5";

const GLOBAL_ATTRIBUTES = new Set(${JSON.stringify([...SAFE_GLOBAL_ATTRIBUTES])});
const ELEMENTS: Readonly<Record<string, Readonly<Record<string, readonly string[]>>>> = ${JSON.stringify(SAFE_DEFAULT_ELEMENTS)};
const HTML_NAMESPACE = parse5Html.NS.HTML;
const NAMESPACES: Readonly<Record<string, string>> = {
  [HTML_NAMESPACE]: "html",
  "http://www.w3.org/2000/svg": "svg",
  "http://www.w3.org/1998/Math/MathML": "mathml",
};

function safeAttribute(name: string, value: string): boolean {
  if (name !== "href" && name !== "cite") return true;
  try { return new URL(value, "https://example.invalid/").protocol !== "javascript:"; }
  catch { return true; }
}

function sanitizeBrowser(parent: ParentNode): void {
  for (const child of Array.from(parent.childNodes)) {
    if (child.nodeType === 8) { child.parentNode?.removeChild(child); continue; }
    if (child.nodeType !== 1) continue;
    const element = child as Element;
    const elements = ELEMENTS[NAMESPACES[element.namespaceURI ?? ""] ?? ""];
    if (elements === undefined || !Object.hasOwn(elements, element.localName)) {
      element.remove();
      continue;
    }
    const local = elements[element.localName] ?? [];
    for (const attribute of Array.from(element.attributes)) {
      if (attribute.namespaceURI !== null ||
        (!GLOBAL_ATTRIBUTES.has(attribute.localName) && !local.includes(attribute.localName)) ||
        !safeAttribute(attribute.localName, attribute.value)) element.removeAttributeNode(attribute);
    }
    sanitizeBrowser(element);
  }
}

function sanitizeServer(parent: DefaultTreeAdapterTypes.ParentNode): void {
  parent.childNodes = parent.childNodes.filter((node) => {
    if (node.nodeName === "#comment") return false;
    if (!("tagName" in node)) return true;
    const elements = ELEMENTS[NAMESPACES[node.namespaceURI] ?? ""];
    if (elements === undefined || !Object.hasOwn(elements, node.tagName)) return false;
    const local = elements[node.tagName] ?? [];
    node.attrs = node.attrs.filter((attribute) =>
      attribute.namespace === undefined &&
      (GLOBAL_ATTRIBUTES.has(attribute.name) || local.includes(attribute.name)) &&
      safeAttribute(attribute.name, attribute.value));
    sanitizeServer(node);
    return true;
  });
}

function browserChildren(parent: ParentNode, projected = false): ReactNode[] {
  return Array.from(parent.childNodes).flatMap((node, index): ReactNode[] => {
    if (node.nodeType === 3) return [node.textContent ?? ""];
    if (node.nodeType !== 1) return [];
    const element = node as Element;
    const attributes = Object.fromEntries(Array.from(element.attributes, ({ name, value }) => [name, value]));
    return [createElement(element.localName, { ...attributes, ...(projected ? { "data-slotted": "" } : {}), key: index }, ...browserChildren(element))];
  });
}

function serverChildren(nodes: readonly DefaultTreeAdapterTypes.ChildNode[], projected = false): ReactNode[] {
  return nodes.flatMap((node, index): ReactNode[] => {
    if (node.nodeName === "#text" && "value" in node) return [node.value];
    if (!("tagName" in node)) return [];
    const attributes = Object.fromEntries(node.attrs.map(({ name, value }) => [name, value]));
    return [createElement(node.tagName, { ...attributes, ...(projected ? { "data-slotted": "" } : {}), key: index }, ...serverChildren(node.childNodes))];
  });
}

function safeNodes(html: string, projected: boolean): ReactNode[] {
  if (typeof document !== "undefined") {
    // Native setHTML() is deliberately not used: Firefox's malformed-table order differs.
    const template = document.createElement("template");
    template.innerHTML = html;
    sanitizeBrowser(template.content);
    return browserChildren(template.content, projected);
  }
  const context = defaultTreeAdapter.createElement("template", HTML_NAMESPACE, []);
  const fragment = parseFragment(context, html, {});
  sanitizeServer(fragment);
  return serverChildren(fragment.childNodes, projected);
}

/** Safe markup as React nodes, with no extra DOM element for inline <template $html>. */
export function SanitizedHtml({ value, projected = false }: { readonly value: string; readonly projected?: boolean }): ReactNode {
  return createElement(Fragment, null, ...safeNodes(value, projected));
}
` });
}
