import type { GeneratedArtifact } from "../generate.js";
import { DATA_URL_SOURCE } from "./shared-generated.js";

const SOURCE = `import React from "react";

export interface DataState<T> {
  readonly pending: boolean;
  readonly value: T | null;
  readonly error: unknown | null;
  readonly ok: boolean;
}

export interface DataReadOptions {
  readonly source?: string;
  readonly definition: string;
  readonly type?: string;
  readonly debounce?: number;
  readonly poll?: number;
  readonly parameters: () => Readonly<Record<string, unknown>>;
}

${DATA_URL_SOURCE}

/** A component-owned declared read; effects never run during server rendering. */
export function useDataRead<T>(options: DataReadOptions): DataState<T> {
  const [state, setState] = React.useState<DataState<T>>({ pending: true, value: null, error: null, ok: false });
  const value = React.useRef<T | null>(null);
  const generation = React.useRef(0);
  const active = React.useRef<{ url: string; abort?: AbortController; timer?: ReturnType<typeof setTimeout> } | undefined>(undefined);

  React.useEffect(() => {
    return () => {
      generation.current += 1;
      active.current?.abort?.abort();
      if (active.current?.timer !== undefined) clearTimeout(active.current.timer);
      active.current = undefined;
    };
  }, []);

  React.useEffect(() => {
    if (options.source === undefined) return;
    const definition = (() => {
      try { return new URL(options.definition, document.baseURI).href; }
      catch { return document.baseURI; }
    })();
    const url = dataURL(options.source, definition, options.parameters());
    if (active.current?.url === url) return;
    active.current?.abort?.abort();
    if (active.current?.timer !== undefined) clearTimeout(active.current.timer);
    const current = ++generation.current;
    const requestState: { url: string; abort?: AbortController; timer?: ReturnType<typeof setTimeout> } = { url };
    active.current = requestState;
    const stale = (): boolean => generation.current !== current;
    const request = async (): Promise<void> => {
      if (stale()) return;
      const controller = new AbortController();
      requestState.abort = controller;
      setState({ pending: true, value: value.current, error: null, ok: false });
      try {
        const response = await fetch(url, { signal: controller.signal });
        if (!response.ok) throw new TypeError(\`Request failed with \${response.status}.\`);
        const next = options.type === "text" || options.type === "string" ? await response.text() : await response.json();
        if (stale()) return;
        value.current = next as T;
        setState({ pending: false, value: value.current, error: null, ok: true });
      } catch (error) {
        if (controller.signal.aborted || stale()) return;
        setState({ pending: false, value: value.current, error, ok: false });
      } finally {
        if (requestState.abort === controller) requestState.abort = undefined;
        if (!stale() && (options.poll ?? 0) > 0) requestState.timer = setTimeout(() => { void request(); }, options.poll);
      }
    };
    if ((options.debounce ?? 0) > 0) requestState.timer = setTimeout(() => { void request(); }, options.debounce);
    else void request();
  });

  return state;
}
`;

export function reactDataArtifact(version: string): GeneratedArtifact {
  return Object.freeze({ path: "react/data.ts", content: `// Generated by HTML Next ${version}. Do not edit.\n${SOURCE}` });
}
