import { DISPATCH_TARGETS_SOURCE } from "./shared-generated.js";
import type { GeneratedArtifact } from "../generate.js";

const DECLARED_SOURCE = `import { acceptsDeclaredEvent } from "./props";
function checkDeclaredDetail(
  name: string,
  detail: unknown,
  type: Parameters<typeof acceptsDeclaredEvent>[1],
): void {
  if (detail !== undefined && !acceptsDeclaredEvent(detail, type)) {
    const message = "Event \`" + name + "\` detail does not satisfy its declared type.";
    throw Object.assign(new Error("HR002: " + message), {
      name: "HtmlDiagnosticError", diagnostic: Object.freeze({ code: "HR002", message }),
    });
  }
}

/** Dispatch a declared event on the component's actual native root. */
export function dispatchDeclared(root: Element | null, name: string, detail: unknown,
  type: Parameters<typeof acceptsDeclaredEvent>[1], init: EventInit): boolean {
  checkDeclaredDetail(name, detail, type);
  return root?.dispatchEvent(new CustomEvent(name, { bubbles: true, composed: true, ...init, detail })) ?? true;
}

/** Accept the action payload once; receivers can mutate its shared reference during delivery. */
export function dispatchDeclaredTargets(recorded: unknown, name: string, detail: unknown,
  type: Parameters<typeof acceptsDeclaredEvent>[1], init: EventInit): void {
  checkDeclaredDetail(name, detail, type);
  dispatchToTargets(recorded, target => {
    target.dispatchEvent(new CustomEvent(name, { bubbles: true, composed: true, ...init, detail }));
  });
}
`;

const SOURCE = `export interface NativeBinding {
  readonly type: string;
  readonly modifiers: readonly string[];
  readonly handler: (event: Event) => void;
}

/** Native listeners preserve DOM propagation, cancellation, and custom-event semantics. */
export function attachNativeEvents(
  element: Element | null,
  bindings: readonly NativeBinding[],
): (() => void) | undefined {
  if (element === null) return undefined;
  const listeners: Array<{ type: string; listener: EventListener; capture: boolean }> = [];
  for (const binding of bindings) {
    const { modifiers } = binding;
    const listener: EventListener = (event) => {
      if (modifiers.includes("self") && event.target !== event.currentTarget) return;
      if (event instanceof MouseEvent) {
        const buttons: Record<string, number> = { left: 0, middle: 1, right: 2 };
        const filters = modifiers.filter((modifier) => modifier in buttons);
        if (filters.length > 0 && !filters.some((filter) => event.button === buttons[filter])) return;
      }
      const systemKeys = ["ctrl", "shift", "alt", "meta"] as const;
      for (const key of systemKeys) {
        if (modifiers.includes(key) && !(event as unknown as Record<string, boolean>)[key + "Key"]) return;
      }
      if (modifiers.includes("exact") && systemKeys.some((key) =>
        !modifiers.includes(key) && (event as unknown as Record<string, boolean>)[key + "Key"],
      )) return;
      if (event instanceof KeyboardEvent) {
        const names: Record<string, string> = {
          enter: "Enter", escape: "Escape", space: " ", tab: "Tab",
          up: "ArrowUp", down: "ArrowDown", left: "ArrowLeft", right: "ArrowRight",
        };
        const filters = modifiers.filter((modifier) => modifier in names);
        if (filters.length > 0 && !filters.some((filter) => event.key === names[filter])) return;
      }
      if (modifiers.includes("prevent")) event.preventDefault();
      if (modifiers.includes("stop")) event.stopPropagation();
      binding.handler(event);
    };
    const capture = modifiers.includes("capture");
    element.addEventListener(binding.type, listener, {
      capture, passive: modifiers.includes("passive"), once: modifiers.includes("once"),
    });
    listeners.push({ type: binding.type, listener, capture });
  }
  return () => {
    for (const { type, listener, capture } of listeners) element.removeEventListener(type, listener, capture);
  };
}
`;

/** Target-independent DOM listeners and declared-event dispatch. */
export function nativeEventsModule(version: string, declared = false): string {
  return `// Generated by HTML Next ${version}. Do not edit.\n${declared ? DECLARED_SOURCE + DISPATCH_TARGETS_SOURCE + "\n" : ""}${SOURCE}`;
}

const REACT_SOURCE = `
/** A ref callback that listens with the component's latest handlers, attached once per element. */
export function useNativeEvents(bindings: readonly NativeBinding[]): (element: Element | null) => (() => void) | undefined {
  const latest = React.useRef(bindings);
  React.useLayoutEffect(() => { latest.current = bindings; });
  return React.useCallback((element: Element | null) => attachNativeEvents(element, latest.current.map((binding, index) =>
    ({ ...binding, handler: (event: Event) => latest.current[index]!.handler(event) }))), []);
}
`;

export function reactEventsArtifact(version: string, declared = false): GeneratedArtifact {
  // The header line stays first; React follows it for the hook.
  const content = nativeEventsModule(version, declared).replace(/^(\/\/[^\n]*\n)/, '$1import React from "react";\n');
  return Object.freeze({ path: "react/events.ts", content: `${content}${REACT_SOURCE}` });
}
