import type { GeneratedArtifact } from "../generate.js";

const SOURCE = `import React from "react";

const registryKey = Symbol.for("nextwebwg.html-next.react.depth.v1");
const registry = globalThis as unknown as Record<symbol, React.Context<number> | undefined>;

/** Share the lowering depth across independently generated React component modules. */
export const NestedDepthContext = registry[registryKey] ??= React.createContext(0);
`;

export function reactDepthArtifact(version: string): GeneratedArtifact {
  return Object.freeze({ path: "react/depth.ts", content: `// Generated by HTML Next ${version}. Do not edit.\n${SOURCE}` });
}
