import type { GeneratedArtifact } from "../generate.js";
import { DATA_URL_SOURCE } from "./shared-generated.js";

const SOURCE = `import { untrack } from "svelte";
import { useConnection } from "./connection.svelte";

export interface DataState<T> {
  readonly pending: boolean;
  readonly value: T | null;
  readonly error: unknown | null;
  readonly ok: boolean;
}

export interface DataReadOptions {
  readonly root: () => Element | null;
  readonly source: string;
  readonly definition: string;
  readonly type?: string;
  readonly debounce?: number;
  readonly poll?: number;
  readonly sources: () => readonly unknown[];
  readonly parameters: () => Readonly<Record<string, unknown>>;
}

${DATA_URL_SOURCE}

/** Svelte owns subscriptions and cleanup; the browser owns requests, cancellation and timers. */
export function useDataRead<T>(options: DataReadOptions): DataState<T> {
  let state = $state.raw<DataState<T>>({ pending: true, value: null, error: null, ok: false });
  let value: T | null = null;
  const connected = useConnection(options.root);
  $effect(() => {
    options.sources();
    if (!connected()) return;
    const definition = (() => {
      try { return new URL(options.definition, document.baseURI).href; }
      catch { return document.baseURI; }
    })();
    let active = true;
    let abort: AbortController | undefined;
    let timer: ReturnType<typeof setTimeout> | undefined;
    const request = async (): Promise<void> => {
      if (!active) return;
      const controller = new AbortController();
      abort = controller;
      state = { pending: true, value, error: null, ok: false };
      try {
        // expr:value is sampled at each send; only from:value subscribes to its inputs.
        const url = dataURL(options.source, definition, untrack(options.parameters));
        const response = await fetch(url, { signal: controller.signal });
        if (!response.ok) throw new TypeError(\`Request failed with \${response.status}.\`);
        const next = options.type === "text" || options.type === "string" ? await response.text() : await response.json();
        if (!active) return;
        value = next as T;
        state = { pending: false, value, error: null, ok: true };
      } catch (error) {
        if (!active || controller.signal.aborted) return;
        state = { pending: false, value, error, ok: false };
      } finally {
        if (abort === controller) abort = undefined;
        if (active && (options.poll ?? 0) > 0) timer = setTimeout(() => { void request(); }, options.poll);
      }
    };
    if ((options.debounce ?? 0) > 0) timer = setTimeout(() => { void request(); }, options.debounce);
    else void request();
    return () => {
      active = false;
      abort?.abort();
      if (timer !== undefined) clearTimeout(timer);
    };
  });
  return {
    get pending() { return state.pending; },
    get value() { return state.value; },
    get error() { return state.error; },
    get ok() { return state.ok; },
  };
}
`;

export function svelteDataArtifact(version: string): GeneratedArtifact {
  return Object.freeze({ path: "svelte/data.svelte.ts", content: `// Generated by HTML Next ${version}. Do not edit.\n${SOURCE}` });
}
