import type { GeneratedArtifact } from "../generate.js";
import { SAFE_HTML_SANITIZER_SOURCE } from "./shared-generated.js";

/** One deterministic sanitizer for Svelte's raw HTML insertion on server and client. */
export function svelteHtmlArtifact(version: string): GeneratedArtifact {
  return Object.freeze({ path: "svelte/html.ts", content: `// Generated by HTML Next ${version}. Do not edit.
import { defaultTreeAdapter, html as parse5Html, parseFragment, serialize, type DefaultTreeAdapterTypes } from "parse5";

${SAFE_HTML_SANITIZER_SOURCE}

/** Keep the last safe output if an expression becomes invalid. */
export function retainedSanitizedHtml(): (value: unknown) => string {
  let previous = "";
  return (value: unknown): string => {
    if (value === Symbol.for("html-next.invalid-result")) return previous;
    const context = defaultTreeAdapter.createElement("template", HTML_NAMESPACE, []);
    const fragment = parseFragment(context, value == null ? "" : String(value), {});
    sanitizeServer(fragment);
    previous = serialize(fragment);
    return previous;
  };
}
` });
}
