import type { GeneratedArtifact } from "../generate.js";
import { DATA_URL_SOURCE } from "./shared-generated.js";

const SOURCE = `import { untrack } from "svelte";
import { useConnection } from "./connection.svelte";

export interface DataState<T> {
  readonly pending: boolean;
  readonly value: T | null;
  readonly error: unknown | null;
  readonly ok: boolean;
}

export interface DataParameter {
  readonly name: string;
  readonly mode: "from" | "expr";
  readonly read: () => unknown;
}

export interface DataReadOptions {
  readonly root: () => Element | null;
  readonly source: string;
  readonly definition: string;
  readonly type?: string;
  readonly debounce?: number;
  readonly poll?: number;
  readonly parameters: readonly DataParameter[];
}

${DATA_URL_SOURCE}

/** Svelte owns subscriptions and cleanup; the browser owns requests, cancellation and timers. */
export function useDataRead<T>(options: DataReadOptions): DataState<T> {
  let state = $state.raw<DataState<T>>({ pending: true, value: null, error: null, ok: false });
  let value: T | null = null;
  const connected = useConnection(options.root);
  const accepted = new Map<string, unknown>();
  const readParameter = (parameter: DataParameter): { value: unknown; valid: boolean } => {
    const candidate = parameter.read();
    if (candidate === Symbol.for('html-next.invalid-result')) {
      return { value: accepted.get(parameter.name) ?? null, valid: false };
    }
    const value = candidate === undefined ? null : candidate;
    accepted.set(parameter.name, value);
    return { value, valid: true };
  };
  const prepared = { valid: false, values: [] as readonly unknown[], key: "" };
  const sources = $derived.by(() => {
    if (!connected()) return prepared.values;
    let valid = true;
    const values = options.parameters.map((parameter) => {
      const result = parameter.mode === "from" ? readParameter(parameter) : untrack(() => readParameter(parameter));
      if (parameter.mode === "from" && !result.valid) valid = false;
      return result.value;
    });
    prepared.valid = valid;
    // Retaining identity keeps an existing request and poll alive on invalid reads, and on valid
    // ones whose from-parameters send what they sent before.
    const key = dataKey(values.filter((_value, index) => options.parameters[index]!.mode === "from"));
    if (valid && key !== prepared.key) {
      prepared.values = values;
      prepared.key = key;
    }
    return prepared.values;
  });
  $effect(() => {
    if (!connected()) return;
    void sources;
    if (!prepared.valid) return;
    const definition = (() => {
      try { return new URL(options.definition, document.baseURI).href; }
      catch { return document.baseURI; }
    })();
    let active = true;
    let abort: AbortController | undefined;
    let timer: ReturnType<typeof setTimeout> | undefined;
    const request = async (): Promise<void> => {
      if (!active) return;
      const controller = new AbortController();
      abort = controller;
      state = { pending: true, value, error: null, ok: false };
      try {
        // expr:value is sampled at each send; only from:value subscribes to its inputs.
        const url = dataURL(options.source, definition, untrack(() => Object.fromEntries(options.parameters.map((parameter) => [parameter.name, readParameter(parameter).value]))));
        const response = await fetch(url, { signal: controller.signal });
        if (!response.ok) throw new TypeError(\`Request failed with \${response.status}.\`);
        const next = options.type === "text" || options.type === "string" ? await response.text() : await response.json();
        if (!active) return;
        value = next as T;
        state = { pending: false, value, error: null, ok: true };
      } catch (error) {
        if (!active || controller.signal.aborted) return;
        state = { pending: false, value, error, ok: false };
      } finally {
        if (abort === controller) abort = undefined;
        if (active && (options.poll ?? 0) > 0) timer = setTimeout(() => { void request(); }, options.poll);
      }
    };
    if ((options.debounce ?? 0) > 0) timer = setTimeout(() => { void request(); }, options.debounce);
    else void request();
    return () => {
      active = false;
      abort?.abort();
      if (timer !== undefined) clearTimeout(timer);
    };
  });
  return {
    get pending() { return state.pending; },
    get value() { return state.value; },
    get error() { return state.error; },
    get ok() { return state.ok; },
  };
}
`;

export function svelteDataArtifact(version: string): GeneratedArtifact {
  return Object.freeze({ path: "svelte/data.svelte.ts", content: `// Generated by HTML Next ${version}. Do not edit.\n${SOURCE}` });
}
