import type { GeneratedArtifact } from "../generate.js";

const SOURCE = `export interface Decoration {
  readonly kind: 'class' | 'style';
  readonly name: string;
  readonly read: () => unknown;
}

export function classText(base: string, decorations: readonly Decoration[]): string {
  const tokens = new Set(base.split(/[ \\t\\r\\n\\f]+/).filter(Boolean));
  for (const decoration of decorations) {
    if (decoration.kind !== 'class') continue;
    const value = decoration.read();
    if (value === Symbol.for('html-next.invalid-result')) continue;
    if (value) tokens.add(decoration.name); else tokens.delete(decoration.name);
  }
  return [...tokens].join(' ');
}
`;

export function svelteDecorationsArtifact(version: string): GeneratedArtifact {
  return Object.freeze({ path: "svelte/decorations.ts", content: `// Generated by HTML Next ${version}. Do not edit.\n${SOURCE}` });
}

/** Standard browser mapping keeps the server CSSOM dependency out of client compilation. */
export function svelteStyleArtifacts(version: string): readonly GeneratedArtifact[] {
  const header = `// Generated by HTML Next ${version}. Do not edit.\n`;
  return Object.freeze([
    Object.freeze({ path: "svelte/style/package.json", content: JSON.stringify({
      type: "module", license: "MIT", sideEffects: false, browser: { "./style.js": "./style.browser.js" },
    }, null, 2) + "\n" }),
    Object.freeze({ path: "svelte/style/style.d.ts", content: header + `import type { Decoration } from '../decorations.js';
export declare function styleText(base: string, decorations: readonly Decoration[]): string;
` }),
    Object.freeze({ path: "svelte/style/style.browser.js", content: header + `export function styleText(base) { return base; }
` }),
    Object.freeze({ path: "svelte/style/style.js", content: header + `import { CSSStyleDeclaration } from 'cssstyle';
import parse from 'css-tree/parser';
export function styleText(base, decorations) {
  const style = new CSSStyleDeclaration();
  const emptyCustom = new Map();
  const declarations = parse(base, { context: 'declarationList', parseValue: false });
  // Literal declarations cascade; the bindings below replace the previous priority.
  for (const declaration of declarations.children) {
    if (declaration.type !== 'Declaration' || declaration.value.type !== 'Raw') continue;
    const priority = declaration.important ? 'important' : '';
    const name = declaration.property;
    const custom = name.startsWith('--');
    const empty = declaration.value.value.trim() === '';
    if (empty && !custom) continue;
    if (custom && priority === '' && (emptyCustom.get(name) ?? style.getPropertyPriority(name)) === 'important') continue;
    if (empty) {
      // Public setProperty removes empty values; CSS literals can declare an empty custom property.
      style.removeProperty(name);
      emptyCustom.set(name, priority);
      continue;
    }
    if (custom) emptyCustom.delete(name);
    const important = priority === '' ? Array.from({ length: style.length }, (_, index) => style.item(index))
      .filter((name) => style.getPropertyPriority(name) === 'important')
      .map((name) => [name, style.getPropertyValue(name)]) : [];
    style.setProperty(declaration.property, declaration.value.value, priority);
    for (const [name, value] of important) style.setProperty(name, value, 'important');
  }
  for (const decoration of decorations) {
    if (decoration.kind !== 'style') continue;
    const value = decoration.read();
    if (value === Symbol.for('html-next.invalid-result')) continue;
    emptyCustom.delete(decoration.name);
    style.setProperty(decoration.name, value == null ? '' : String(value));
  }
  return [style.cssText, ...[...emptyCustom].map(([name, priority]) => name + ': ' + (priority === 'important' ? '!important' : '') + ';')].filter(Boolean).join(' ');
}
` }),
  ]);
}
