import type { GeneratedArtifact } from "../generate.js";
import { NATIVE_CONNECTION_SOURCE } from "./native-connection-source.js";

const SOURCE = `import { untrack } from "svelte";

${NATIVE_CONNECTION_SOURCE.replace("function observeConnection", "export function observeConnection")}
/** Native connectivity is the remaining gap between framework ownership and DOM lifetimes. */
export function useConnection(root: () => Element | null): () => boolean {
  let connected = $state(false);
  $effect(() => {
    const element = root();
    const synchronize = (): void => { connected = element?.isConnected === true; };
    untrack(synchronize);
    if (element === null) return;
    return observeConnection(element, synchronize);
  });
  return () => connected;
}
`;

export function svelteConnectionArtifact(version: string): GeneratedArtifact {
  return Object.freeze({ path: "svelte/connection.svelte.ts", content: `// Generated by HTML Next ${version}. Do not edit.\n${SOURCE}` });
}
