import type { GeneratedArtifact } from "../generate.js";

const SOURCE = `/** Native Svelte derived tracking, with the shared diagnostic at a recursive read. */
export function cycleCheckedComputed<T>(compute: () => T): { get(): T } {
  // Svelte compares deriveds with ===; a box kept while the result is Object.is-equal stops NaN too.
  let box: { readonly value: T } | undefined;
  let value = $derived.by(() => {
    const next = compute();
    return box !== undefined && Object.is(box.value, next) ? box : (box = { value: next });
  });
  let reading = false;
  return { get(): T {
    if (reading) {
      const message = "A reactive computed value depends on itself.";
      throw Object.assign(new Error("HR006: " + message), {
        name: "HtmlDiagnosticError", diagnostic: Object.freeze({ code: "HR006", message }),
      });
    }
    reading = true;
    try { return value.value; }
    finally { reading = false; }
  } };
}
`;

export function svelteReactivityArtifact(version: string): GeneratedArtifact {
  return Object.freeze({ path: "svelte/reactivity.svelte.ts", content: `// Generated by HTML Next ${version}. Do not edit.\n${SOURCE}` });
}
