import type { ComponentDefinition } from "../template.js";
import { rootArms } from "../template.js";
import type { PropContract } from "../types.js";
import { getDomInterface } from "../platform.js";
import { dependentPropTypeSource, selectorGenerics } from "./shared.js";
import { targetComponent } from "./backend.js";
import { blockPlan, emitBlocks } from "./vanilla-blocks.js";
import type { Invoked } from "../generate.js";

function js(value: string): string {
  return JSON.stringify(value);
}

function tsKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : js(name);
}

function optional(prop: PropContract): string {
  return prop.required ? "" : "?";
}

export function generateVanilla(
  definition: ComponentDefinition,
  version: string,
  noContextReaders = false,
  invocations?: ReadonlyMap<string, Invoked>,
  /** The build enables the `transitions` extension. */
  transitions = false,
  /** The factory also adopts a server-rendered root. */
  hydrate = false,
): { readonly module: string; readonly declaration: string } {
  const { contract, template } = definition;
  const target = targetComponent(definition);
  const props = target.props.map(({ name, contract }) => [name, contract] as const);
  const generics = selectorGenerics(contract.props);
  const parameters = new Map(generics.map(({ from, parameter }) => [from, parameter]));
  const genericDeclaration = generics.length === 0 ? "" : `<${generics.map(({ declaration }) => declaration).join(", ")}>`;
  const genericReference = generics.length === 0 ? "" : `<${generics.map(({ parameter }) => parameter).join(", ")}>`;
  const hasRequired = props.some(([, prop]) => prop.required);
  // A root `$match` renders the arm the props choose, so its root type is the common one.
  const arms = rootArms(template);
  const domType = arms === undefined ? getDomInterface(contract.nativeElement) ?? "HTMLElement" : "HTMLElement";
  const elementType = `${contract.name}Element`;
  const declaration = [
    `// Generated by HTML Next ${version} for Vanilla DOM. Do not edit.`,
    `export interface ${contract.name}EventMap {`,
    ...target.events.map((event) => `  ${tsKey(event.name)}: CustomEvent<${event.detailType}>;`),
    "}",
    `export interface ${elementType} extends ${domType} {`,
    `  addEventListener<K extends keyof ${contract.name}EventMap>(type: K, listener: (this: ${elementType}, event: ${contract.name}EventMap[K]) => unknown, options?: boolean | AddEventListenerOptions): void;`,
    `  removeEventListener<K extends keyof ${contract.name}EventMap>(type: K, listener: (this: ${elementType}, event: ${contract.name}EventMap[K]) => unknown, options?: boolean | EventListenerOptions): void;`,
    "}",
    `export interface ${contract.name}Props${genericDeclaration} {`,
    ...props.map(
      ([name, prop]) => `  ${tsKey(name)}${optional(prop)}: ${parameters.get(name) ?? dependentPropTypeSource(prop, parameters)};`,
    ),
    "  attributes?: Readonly<Record<string, string | number | boolean | null | undefined>>;",
    "  children?: readonly (string | Node)[];",
    "  slots?: Readonly<Record<string, readonly (string | Node)[]>>;",
    "}",
    `export declare function create${contract.name}${genericDeclaration}(props${hasRequired ? "" : "?"}: ${contract.name}Props${genericReference}): ${elementType};`,
    "",
  ].join("\n");

  // The root's literal attributes: the invocation's attributes win over them, and class and style combine.
  const rootLines = template.attributes.flatMap((attribute) => {
    if (attribute.kind !== "literal") return [];
    const name = js(attribute.name);
    const value = js(attribute.value);
    return [attribute.name === "class" || attribute.name === "style"
      ? `  element.setAttribute(${name}, [${value}, element.getAttribute(${name})].filter(Boolean).join(${js(attribute.name === "class" ? " " : "; ")}));`
      : `  if (!element.hasAttribute(${name})) element.setAttribute(${name}, ${value});`];
  });
  return { module: emitBlocks(blockPlan(definition, invocations, transitions), definition, version, rootLines, invocations, noContextReaders, hydrate), declaration };
}
