import { SAFE_DEFAULT_ELEMENTS, SAFE_GLOBAL_ATTRIBUTES } from "../sanitizer-default.js";

export const VUE_HTML_PATH = "vue/html.ts";
export const VUE_HTML_SPECIFIER = "./html";

export function importsVueHtml(source: string): boolean {
  return new RegExp(`from ['"]${VUE_HTML_SPECIFIER}['"]`).test(source);
}

/** Generated, feature-specific Vue output; no HTML Next runtime is imported by the consumer. */
export function vueHtmlModule(version: string): string {
  return `// Generated by HTML Next ${version}. Do not edit.
import { defineComponent, Fragment, getCurrentInstance, h, type VNode } from "vue";
import { defaultTreeAdapter, html as parse5Html, parseFragment, type DefaultTreeAdapterTypes } from "parse5";

const GLOBAL_ATTRIBUTES = new Set(${JSON.stringify([...SAFE_GLOBAL_ATTRIBUTES])});
const ELEMENTS: Readonly<Record<string, Readonly<Record<string, readonly string[]>>>> = ${JSON.stringify(SAFE_DEFAULT_ELEMENTS)};
const HTML_NAMESPACE = parse5Html.NS.HTML;
const NAMESPACES: Readonly<Record<string, string>> = {
  [HTML_NAMESPACE]: "html",
  "http://www.w3.org/2000/svg": "svg",
  "http://www.w3.org/1998/Math/MathML": "mathml",
};

function safeAttribute(name: string, value: string): boolean {
  if (name !== "href" && name !== "cite") return true;
  try { return new URL(value, "https://example.invalid/").protocol !== "javascript:"; }
  catch { return true; }
}

function sanitizeBrowser(parent: ParentNode): void {
  for (const child of Array.from(parent.childNodes)) {
    if (child.nodeType === 8) { child.parentNode?.removeChild(child); continue; }
    if (child.nodeType !== 1) continue;
    const element = child as Element;
    const namespace = NAMESPACES[element.namespaceURI ?? ""];
    const elements = namespace === undefined ? undefined : ELEMENTS[namespace];
    if (elements === undefined || !Object.hasOwn(elements, element.localName)) {
      element.remove();
      continue;
    }
    const local = elements[element.localName] ?? [];
    for (const attribute of Array.from(element.attributes)) {
      if (attribute.namespaceURI !== null ||
        (!GLOBAL_ATTRIBUTES.has(attribute.localName) && !local.includes(attribute.localName)) ||
        !safeAttribute(attribute.localName, attribute.value)) element.removeAttributeNode(attribute);
    }
    sanitizeBrowser(element);
  }
}

function sanitizeServer(parent: DefaultTreeAdapterTypes.ParentNode): void {
  parent.childNodes = parent.childNodes.filter((node) => {
    if (node.nodeName === "#comment") return false;
    if (!("tagName" in node)) return true;
    const namespace = NAMESPACES[node.namespaceURI];
    const elements = namespace === undefined ? undefined : ELEMENTS[namespace];
    if (elements === undefined || !Object.hasOwn(elements, node.tagName)) return false;
    const local = elements[node.tagName] ?? [];
    node.attrs = node.attrs.filter((attribute) =>
      attribute.namespace === undefined &&
      (GLOBAL_ATTRIBUTES.has(attribute.name) || local.includes(attribute.name)) &&
      safeAttribute(attribute.name, attribute.value));
    sanitizeServer(node);
    return true;
  });
}

type Child = VNode | string;

function browserChildren(parent: ParentNode, scopeId: string | undefined): Child[] {
  return Array.from(parent.childNodes).flatMap((node): Child[] => {
    if (node.nodeType === 3) return [node.textContent ?? ""];
    if (node.nodeType !== 1) return [];
    const element = node as Element;
    const attributes = Object.fromEntries(Array.from(element.attributes, ({ name, value }) => [name, value]));
    if (scopeId !== undefined) attributes[scopeId] = "";
    return [h(element.localName, attributes, browserChildren(element, scopeId))];
  });
}

function serverChildren(nodes: readonly DefaultTreeAdapterTypes.ChildNode[], scopeId: string | undefined): Child[] {
  return nodes.flatMap((node): Child[] => {
    if (node.nodeName === "#text" && "value" in node) return [node.value];
    if (!("tagName" in node)) return [];
    const attributes = Object.fromEntries(node.attrs.map(({ name, value }) => [name, value]));
    if (scopeId !== undefined) attributes[scopeId] = "";
    return [h(node.tagName, attributes, serverChildren(node.childNodes, scopeId))];
  });
}

function safeNodes(html: string, scopeId: string | undefined): Child[] {
  if (typeof document !== "undefined") {
    // Native setHTML() is deliberately not used: Firefox's malformed-table order differs.
    const template = document.createElement("template");
    template.innerHTML = html;
    sanitizeBrowser(template.content);
    return browserChildren(template.content, scopeId);
  }
  const context = defaultTreeAdapter.createElement("template", HTML_NAMESPACE, []);
  const fragment = parseFragment(context, html, {});
  sanitizeServer(fragment);
  return serverChildren(fragment.childNodes, scopeId);
}

/** Wrapperless safe markup, rendered as Vue nodes on both the client and server. */
export const SanitizedHtml = defineComponent({
  name: "HtmlNextSanitizedHtml",
  props: { value: { type: String, required: true } },
  setup(props) {
    const parent = getCurrentInstance()?.parent?.type as { __scopeId?: string } | undefined;
    const scopeId = parent?.__scopeId;
    return () => h(Fragment, { key: props.value }, safeNodes(props.value, scopeId));
  },
});
`;
}
