import { SAFE_HTML_SANITIZER_SOURCE } from "./shared-generated.js";

export const VUE_HTML_PATH = "vue/html.ts";
export const VUE_HTML_SPECIFIER = "./html";

export function importsVueHtml(source: string): boolean {
  return new RegExp(`from ['"]${VUE_HTML_SPECIFIER}['"]`).test(source);
}

/** Generated, feature-specific Vue output; no HTML Next runtime is imported by the consumer. */
export function vueHtmlModule(version: string): string {
  return `// Generated by HTML Next ${version}. Do not edit.
import { defineComponent, Fragment, getCurrentInstance, h, type VNode } from "vue";
import { defaultTreeAdapter, html as parse5Html, parseFragment, type DefaultTreeAdapterTypes } from "parse5";

${SAFE_HTML_SANITIZER_SOURCE}

type Child = VNode | string;

function browserChildren(parent: ParentNode, scopeId: string | undefined): Child[] {
  return Array.from(parent.childNodes).flatMap((node): Child[] => {
    if (node.nodeType === 3) return [node.textContent ?? ""];
    if (node.nodeType !== 1) return [];
    const element = node as Element;
    const attributes = Object.fromEntries(Array.from(element.attributes, ({ name, value }) => [name, value]));
    if (scopeId !== undefined) attributes[scopeId] = "";
    return [h(element.localName, attributes, browserChildren(element, scopeId))];
  });
}

function serverChildren(nodes: readonly DefaultTreeAdapterTypes.ChildNode[], scopeId: string | undefined): Child[] {
  return nodes.flatMap((node): Child[] => {
    if (node.nodeName === "#text" && "value" in node) return [node.value];
    if (!("tagName" in node)) return [];
    const attributes = Object.fromEntries(node.attrs.map(({ name, value }) => [name, value]));
    if (scopeId !== undefined) attributes[scopeId] = "";
    return [h(node.tagName, attributes, serverChildren(node.childNodes, scopeId))];
  });
}

function safeNodes(html: string, scopeId: string | undefined): Child[] {
  if (typeof document !== "undefined") {
    // Native setHTML() is deliberately not used: Firefox's malformed-table order differs.
    const template = document.createElement("template");
    template.innerHTML = html;
    sanitizeBrowser(template.content);
    return browserChildren(template.content, scopeId);
  }
  const context = defaultTreeAdapter.createElement("template", HTML_NAMESPACE, []);
  const fragment = parseFragment(context, html, {});
  sanitizeServer(fragment);
  return serverChildren(fragment.childNodes, scopeId);
}

/** Wrapperless safe markup, rendered as Vue nodes on both the client and server. */
export const SanitizedHtml = defineComponent({
  name: "HtmlNextSanitizedHtml",
  props: { value: { type: String, required: true } },
  setup(props) {
    const parent = getCurrentInstance()?.parent?.type as { __scopeId?: string } | undefined;
    const scopeId = parent?.__scopeId;
    return () => h(Fragment, { key: props.value }, safeNodes(props.value, scopeId));
  },
});
`;
}
