/**
 * Measures the Vue, React and Svelte converter output for the conformance corpus: generated bytes
 * (raw and gzip) and the generated-code patterns that inflate it. `--bundle` also reports each Vue
 * component as an application ships it: compiled, bundled with the helpers it imports, minified and
 * tree-shaken, Vue itself external, and every component of each target in one application bundle.
 * Run with `pnpm exec tsx` before and after a converter change.
 */
import { gzipSync } from "node:zlib";

import { compileScript, parse as parseVue } from "@vue/compiler-sfc";
import { build, transform, type Plugin } from "esbuild";
import { compile as compileSvelte, compileModule } from "svelte/compiler";
import { parseFragment } from "parse5";

import * as generate from "../src/generate.js";
import { generateReactConversion, generateSvelteConversion, generateVueComponent } from "../src/generate.js";
import { parseComponent } from "../src/source-parser.js";
import { cases } from "../tests/conformance/cases.js";

const patterns: Readonly<Record<string, RegExp>> = {
  authoredChecks: /htmlNextAuthoredCheck\d*\(/g,
  retained: /RetainedValue|retainedValue\(|guardedPrevious/g,
  hydrationRoot: /HR005/g,
  prototypeNames: /__proto__/g,
};

function definitionOf(source: string): string | undefined {
  const carrier = parseFragment(source, { sourceCodeLocationInfo: true }).childNodes.find((node) =>
    "tagName" in node && node.tagName === "template" && node.attrs.some((attribute) => attribute.name === "component"));
  const location = carrier?.sourceCodeLocation;
  return location === undefined || location === null ? undefined : source.slice(location.startOffset, location.endOffset);
}

const totals = new Map<string, { files: number; bytes: number; gzip: number; lines: number; counts: Record<string, number> }>();
const add = (target: string, text: string): void => {
  const total = totals.get(target) ?? { files: 0, bytes: 0, gzip: 0, lines: 0, counts: Object.fromEntries(Object.keys(patterns).map((name) => [name, 0])) };
  total.files++;
  total.bytes += Buffer.byteLength(text);
  total.gzip += gzipSync(text).length;
  total.lines += text.split("\n").length;
  for (const [name, pattern] of Object.entries(patterns)) total.counts[name]! += text.match(pattern)?.length ?? 0;
  totals.set(target, total);
};

/** A converted component's helper imports, resolved to the modules a build ships beside it. */
const helpers: Plugin = { name: "vue-helpers", setup(bundler) {
  const artifact = (name: string): string => {
    const make = (generate as unknown as Record<string, (() => { content: string }) | undefined>)[`vue${name[0]!.toUpperCase()}${name.slice(1)}Artifact`];
    return make?.().content ?? "";
  };
  bundler.onResolve({ filter: /^\.\/(?:host|props|html|control)$/ }, (args) => ({ path: args.path.slice(2), namespace: "vue-helpers" }));
  bundler.onLoad({ filter: /.*/, namespace: "vue-helpers" }, (args) => ({ contents: artifact(args.path), loader: "ts" }));
} };

async function shipped(source: string, id: string): Promise<number> {
  const { descriptor } = parseVue(source, { filename: `${id}.vue` });
  const script = compileScript(descriptor, { id, inlineTemplate: true });
  const bundle = await build({ stdin: { contents: script.content, loader: "ts" }, bundle: true, write: false, format: "esm",
    minify: true, treeShaking: true, external: ["vue", "*.vue"], plugins: [helpers], logLevel: "silent" });
  return gzipSync(bundle.outputFiles[0]!.contents).length;
}

/** Every component in one application bundle, sharing the helpers they import. */
async function application(sources: readonly string[]): Promise<number> {
  const modules = sources.map((source, index) => compileScript(parseVue(source, { filename: `c${index}.vue` }).descriptor, { id: `c${index}`, inlineTemplate: true }).content);
  const entry: Plugin = { name: "entry", setup(bundler) {
    bundler.onResolve({ filter: /^component:\d+$/ }, (args) => ({ path: args.path, namespace: "component" }));
    bundler.onLoad({ filter: /.*/, namespace: "component" }, (args) => ({ contents: modules[Number(args.path.slice("component:".length))]!, loader: "ts", resolveDir: "." }));
  } };
  const bundle = await build({ stdin: { contents: modules.map((_module, index) => `export { default as C${index} } from "component:${index}";`).join("\n"), loader: "ts" },
    bundle: true, write: false, format: "esm", minify: true, treeShaking: true, external: ["vue", "parse5", "*.vue"], plugins: [entry, helpers], logLevel: "silent" });
  return gzipSync(bundle.outputFiles[0]!.contents).length;
}

/** A converted React component's helper imports, resolved to the modules a build ships beside it. */
const reactHelpers: Plugin = { name: "react-helpers", setup(bundler) {
  bundler.onResolve({ filter: /^\.\/(?:render|events|context|props|control|data|html|host|depth)$/ }, (args) => ({ path: args.path.slice(2), namespace: "react-helpers" }));
  bundler.onLoad({ filter: /.*/, namespace: "react-helpers" }, (args) => {
    const make = (generate as unknown as Record<string, ((declared?: boolean) => { content: string }) | undefined>)[`react${args.path[0]!.toUpperCase()}${args.path.slice(1)}Artifact`];
    return { contents: make?.(true).content ?? "", loader: "tsx" };
  });
} };

/** Every React component in one application bundle, sharing the helpers they import. */
async function reactApplication(sources: readonly string[]): Promise<number> {
  const entry: Plugin = { name: "entry", setup(bundler) {
    bundler.onResolve({ filter: /^component:\d+$/ }, (args) => ({ path: args.path, namespace: "component" }));
    bundler.onLoad({ filter: /.*/, namespace: "component" }, (args) => ({ contents: sources[Number(args.path.slice("component:".length))]!, loader: "tsx", resolveDir: "." }));
  } };
  const bundle = await build({ stdin: { contents: sources.map((_source, index) => `export { default as C${index} } from "component:${index}";`).join("\n"), loader: "ts" },
    bundle: true, write: false, format: "esm", minify: true, treeShaking: true, jsx: "automatic", external: ["react", "react/*", "react-dom", "parse5", "*.tsx", "*.css"],
    plugins: [entry, reactHelpers], logLevel: "silent" });
  return gzipSync(bundle.outputFiles[0]!.contents).length;
}

/** A converted Svelte component's helper imports, resolved to the modules a build ships beside it. */
const svelteHelpers: Plugin = { name: "svelte-helpers", setup(bundler) {
  bundler.onResolve({ filter: /^\.\/(?:render|events|props|control|data|html|host|decorations|reactivity|connection)(?:\.svelte)?$/ }, (args) => ({ path: args.path.slice(2).replace(/\.svelte$/, ""), namespace: "svelte-helpers" }));
  bundler.onLoad({ filter: /.*/, namespace: "svelte-helpers" }, async (args) => {
    const make = (generate as unknown as Record<string, ((declared?: boolean) => { path: string; content: string }) | undefined>)[`svelte${args.path[0]!.toUpperCase()}${args.path.slice(1)}Artifact`];
    const artifact = make?.(true);
    if (artifact === undefined) return { contents: "", loader: "ts" };
    if (!artifact.path.endsWith(".svelte.ts")) return { contents: artifact.content, loader: "ts" };
    // Rune modules compile through Svelte, as a Svelte build does.
    const script = (await transform(artifact.content, { loader: "ts" })).code;
    return { contents: compileModule(script, { filename: artifact.path, generate: "client" }).js.code, loader: "js" };
  });
} };

/** Every Svelte component in one application bundle, compiled for the client, sharing the helpers they import. */
async function svelteApplication(sources: readonly string[]): Promise<number> {
  const entry: Plugin = { name: "entry", setup(bundler) {
    bundler.onResolve({ filter: /^component:\d+$/ }, (args) => ({ path: args.path, namespace: "component" }));
    bundler.onLoad({ filter: /.*/, namespace: "component" }, (args) => ({ contents: compileSvelte(sources[Number(args.path.slice("component:".length))]!, { filename: `${args.path}.svelte`, generate: "client" }).js.code, loader: "js", resolveDir: "." }));
  } };
  const bundle = await build({ stdin: { contents: sources.map((_source, index) => `export { default as C${index} } from "component:${index}";`).join("\n"), loader: "ts" },
    bundle: true, write: false, format: "esm", minify: true, treeShaking: true, external: ["svelte", "svelte/*", "parse5", "cssstyle", "css-tree", "*.svelte", "*.css", "./style/*"],
    plugins: [entry, svelteHelpers], logLevel: "silent" });
  return gzipSync(bundle.outputFiles[0]!.contents).length;
}

const svelteSources: string[] = [];
const reactSources: string[] = [];
const vueSources: string[] = [];
const bundled = process.argv.includes("--bundle");
let shippedGzip = 0;
let skipped = 0;
for (const testCase of cases) {
  if (!("probe" in testCase.expect)) continue;
  const source = definitionOf(testCase.source);
  if (source === undefined) continue;
  let definition;
  try { definition = parseComponent(source, testCase.name); } catch { skipped++; continue; }
  for (const [target, generate] of [
    ["vue", () => generateVueComponent(definition)],
    ["react", () => generateReactConversion(definition).component],
    ["svelte", () => generateSvelteConversion(definition).component],
  ] as const) {
    try { add(target, generate()); } catch { skipped++; }
  }
  if (bundled) {
    try {
      const source = generateVueComponent(definition);
      shippedGzip += await shipped(source, `c${vueSources.length}`);
      vueSources.push(source);
    } catch { skipped++; }
    try { reactSources.push(generateReactConversion(definition).component); } catch { skipped++; }
    try { svelteSources.push(generateSvelteConversion(definition).component); } catch { skipped++; }
  }
}
console.log(JSON.stringify({ skipped, targets: Object.fromEntries(totals), ...(bundled ? { vueShippedGzip: shippedGzip, vueApplicationGzip: await application(vueSources), reactApplicationGzip: await reactApplication(reactSources), svelteApplicationGzip: await svelteApplication(svelteSources) } : {}) }, null, 2));
