/**
 * Measures the Vue, React and Svelte converter output for the conformance corpus: generated bytes
 * (raw and gzip) and the generated-code patterns that inflate it. `--bundle` also reports each Vue
 * component as an application ships it: compiled, bundled with the helpers it imports, minified and
 * tree-shaken, Vue itself external. Run with `pnpm exec tsx` before and after a converter change.
 */
import { gzipSync } from "node:zlib";

import { compileScript, parse as parseVue } from "@vue/compiler-sfc";
import { build, type Plugin } from "esbuild";
import { parseFragment } from "parse5";

import * as generate from "../src/generate.js";
import { generateReactConversion, generateSvelteConversion, generateVueComponent } from "../src/generate.js";
import { parseComponent } from "../src/source-parser.js";
import { cases } from "../tests/conformance/cases.js";

const patterns: Readonly<Record<string, RegExp>> = {
  authoredChecks: /htmlNextAuthoredCheck\d*\(/g,
  retained: /RetainedValue|retainedValue\(|guardedPrevious/g,
  hydrationRoot: /HR005/g,
  prototypeNames: /__proto__/g,
};

function definitionOf(source: string): string | undefined {
  const carrier = parseFragment(source, { sourceCodeLocationInfo: true }).childNodes.find((node) =>
    "tagName" in node && node.tagName === "template" && node.attrs.some((attribute) => attribute.name === "component"));
  const location = carrier?.sourceCodeLocation;
  return location === undefined || location === null ? undefined : source.slice(location.startOffset, location.endOffset);
}

const totals = new Map<string, { files: number; bytes: number; gzip: number; lines: number; counts: Record<string, number> }>();
const add = (target: string, text: string): void => {
  const total = totals.get(target) ?? { files: 0, bytes: 0, gzip: 0, lines: 0, counts: Object.fromEntries(Object.keys(patterns).map((name) => [name, 0])) };
  total.files++;
  total.bytes += Buffer.byteLength(text);
  total.gzip += gzipSync(text).length;
  total.lines += text.split("\n").length;
  for (const [name, pattern] of Object.entries(patterns)) total.counts[name]! += text.match(pattern)?.length ?? 0;
  totals.set(target, total);
};

/** A converted component's helper imports, resolved to the modules a build ships beside it. */
const helpers: Plugin = { name: "vue-helpers", setup(bundler) {
  const artifact = (name: string): string => {
    const make = (generate as unknown as Record<string, (() => { content: string }) | undefined>)[`vue${name[0]!.toUpperCase()}${name.slice(1)}Artifact`];
    return make?.().content ?? "";
  };
  bundler.onResolve({ filter: /^\.\/(?:host|props|html|control)$/ }, (args) => ({ path: args.path.slice(2), namespace: "vue-helpers" }));
  bundler.onLoad({ filter: /.*/, namespace: "vue-helpers" }, (args) => ({ contents: artifact(args.path), loader: "ts" }));
} };

async function shipped(source: string, id: string): Promise<number> {
  const { descriptor } = parseVue(source, { filename: `${id}.vue` });
  const script = compileScript(descriptor, { id, inlineTemplate: true });
  const bundle = await build({ stdin: { contents: script.content, loader: "ts" }, bundle: true, write: false, format: "esm",
    minify: true, treeShaking: true, external: ["vue", "*.vue"], plugins: [helpers], logLevel: "silent" });
  return gzipSync(bundle.outputFiles[0]!.contents).length;
}

/** Every component in one application bundle, sharing the helpers they import. */
async function application(sources: readonly string[]): Promise<number> {
  const modules = sources.map((source, index) => compileScript(parseVue(source, { filename: `c${index}.vue` }).descriptor, { id: `c${index}`, inlineTemplate: true }).content);
  const entry: Plugin = { name: "entry", setup(bundler) {
    bundler.onResolve({ filter: /^component:\d+$/ }, (args) => ({ path: args.path, namespace: "component" }));
    bundler.onLoad({ filter: /.*/, namespace: "component" }, (args) => ({ contents: modules[Number(args.path.slice("component:".length))]!, loader: "ts", resolveDir: "." }));
  } };
  const bundle = await build({ stdin: { contents: modules.map((_module, index) => `export { default as C${index} } from "component:${index}";`).join("\n"), loader: "ts" },
    bundle: true, write: false, format: "esm", minify: true, treeShaking: true, external: ["vue", "*.vue"], plugins: [entry, helpers], logLevel: "silent" });
  return gzipSync(bundle.outputFiles[0]!.contents).length;
}

const vueSources: string[] = [];
const bundled = process.argv.includes("--bundle");
let shippedGzip = 0;
let skipped = 0;
for (const testCase of cases) {
  if (!("probe" in testCase.expect)) continue;
  const source = definitionOf(testCase.source);
  if (source === undefined) continue;
  let definition;
  try { definition = parseComponent(source, testCase.name); } catch { skipped++; continue; }
  for (const [target, generate] of [
    ["vue", () => generateVueComponent(definition)],
    ["react", () => generateReactConversion(definition).component],
    ["svelte", () => generateSvelteConversion(definition).component],
  ] as const) {
    try { add(target, generate()); } catch { skipped++; }
  }
  if (bundled) {
    try {
      const source = generateVueComponent(definition);
      shippedGzip += await shipped(source, `c${vueSources.length}`);
      vueSources.push(source);
    } catch { skipped++; }
  }
}
console.log(JSON.stringify({ skipped, targets: Object.fromEntries(totals), ...(bundled ? { vueShippedGzip: shippedGzip, vueApplicationGzip: await application(vueSources) } : {}) }, null, 2));
