import type { ComponentDefinition, TemplateNode } from "../template.js";
import {
  escapeHtml,
  frameworkBindingExpression,
  isVoidElement,
  literalAttribute,
  provenanceAttributes,
  propKey,
  quote,
  serializedDefinition,
  typeSource,
} from "./shared.js";
import { targetComponent } from "./backend.js";

function access(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? `props.${name}` : `props['${name}']`;
}

function renderNode(
  node: TemplateNode,
  definition: ComponentDefinition,
  depth: number,
): string {
  if (node.kind === "text") return escapeHtml(node.value);
  if (node.kind === "slot") {
    const attributes = node.name === undefined ? "" : ` name=${literalAttribute(node.name)}`;
    const dynamic = node.nameExpression === undefined ? "" : ` :name=${quote("''")}`;
    const fallback = node.fallback?.map((child) => renderNode(child, definition, depth + 1)).join("\n") ?? "";
    return fallback === ""
      ? `<slot${attributes}${dynamic}></slot>`
      : `<slot${attributes}${dynamic}>${fallback}</slot>`;
  }
  const indent = "  ".repeat(depth);
  const attributes = node.attributes.map((attribute) => {
    if (attribute.kind === "literal") return `${attribute.name}=${literalAttribute(attribute.value)}`;
    if (attribute.kind === "directive") return "";
    const value = definition.contract.props[attribute.expression] === undefined
      ? "undefined"
      : access(attribute.expression);
    const expression = frameworkBindingExpression(
      attribute,
      definition.contract.props,
      node.name,
      value,
      "''",
    );
    return `:${attribute.name}=${quote(expression)}`;
  });
  attributes.push(...provenanceAttributes(definition.contract.tag));
  const open = `<${node.name}${attributes.filter(Boolean).length === 0 ? "" : ` ${attributes.filter(Boolean).join(" ")}`}>`;
  if (isVoidElement(node.name)) return open;
  const children = node.children.map((child) => renderNode(child, definition, depth + 1)).join("\n");
  return children === "" ? `${open}</${node.name}>` : `${open}\n${indent}  ${children}\n${indent}</${node.name}>`;
}

export function generateVue(definition: ComponentDefinition, version: string): string {
  const { contract, template } = definition;
  const target = targetComponent(definition);
  const props = target.props.map(({ name, contract }) => [name, contract] as const);
  const defaults = props.filter(([, prop]) => "default" in prop);
  const polymorphic = target.polymorphic;
  const define = [
    "defineProps<{",
    ...props.map(([name, prop]) => `  ${propKey(name)}${prop.required ? "" : "?"}: ${typeSource(prop.type)}${prop.required ? "" : " | null"};`),
    ...(polymorphic ? [`  as?: ${definition.root!.kind === "native" ? definition.root!.choices.map(quote).join(" | ") : "never"};`] : []),
    "}>()",
  ].join("\n");
  const declaration = defaults.length === 0
    ? `const props = ${define};`
    : `const props = withDefaults(${define}, {\n${defaults.map(([name, prop]) => `  ${propKey(name)}: ${JSON.stringify(prop.default)},`).join("\n")}\n});`;
  const rootAttributes = [...provenanceAttributes(contract.tag, true), ...template.attributes.map((attribute) => {
    if (attribute.kind === "literal") return `${attribute.name}=${literalAttribute(attribute.value)}`;
    if (attribute.kind === "directive") return "";
    const value = contract.props[attribute.expression] === undefined ? "undefined" : access(attribute.expression);
    const expression = frameworkBindingExpression(
      attribute,
      contract.props,
      template.name,
      value,
      "''",
    );
    return `:${attribute.name}=${quote(expression)}`;
  }), 'ref="root"'].filter(Boolean);
  const children = template.children.map((child) => renderNode(child, definition, 1)).join("\n");
  const emitDeclaration = target.events.length === 0 ? [] : [
    "const emit = defineEmits<{",
    ...target.events.map((event) => `  ${quote(event.name)}: [detail: ${event.detailType}];`),
    "}>();",
  ];
  const eventListeners = target.events.map((event, index) =>
    `const eventListener${index} = (event: Event) => emit(${quote(event.name)}, (event as CustomEvent<${event.detailType}>).detail);`
  );
  const expose = target.methods.length === 0 ? [] : [
    "defineExpose({",
    ...target.methods.map((method) =>
      `  ${propKey(method.name)}: (): ${method.returnType} => (root.value as unknown as Record<string, () => ${method.returnType}>)[${quote(method.name)}](),`
    ),
    "});",
  ];

  return [
    `<!-- Generated by HTML Next ${version} for Vue 3.5. Do not edit. -->`,
    '<script setup lang="ts">',
    'import { onMounted, onUnmounted, ref, watchEffect } from "vue";',
    'import { attachComponent } from "@nextwebwg/html/runtime";',
    'import type { ComponentDefinition } from "@nextwebwg/html";',
    ...(definition.controller === undefined ? [] : [`import * as controller from ${quote(definition.controller)};`]),
    `import "../styles/${contract.tag}.css";`,
    "",
    "defineOptions({ inheritAttrs: false });",
    "",
    declaration,
    ...emitDeclaration,
    `const definition = ${serializedDefinition(definition)} as unknown as ComponentDefinition;`,
    "const root = ref<Element>();",
    ...eventListeners,
    "let detach: undefined | (() => void);",
    "onMounted(() => {",
    "  if (root.value == null) return;",
    "  detach = attachComponent(root.value, definition, { props,",
    ...(definition.controller === undefined ? [] : ["    controller,"]),
    "  });",
    ...target.events.map((event, index) =>
      `  root.value.addEventListener(${quote(event.name)}, eventListener${index});`
    ),
    "});",
    "watchEffect(() => {",
    "  if (root.value == null) return;",
    `  for (const name of ${JSON.stringify(props.map(([name]) => name))}) (root.value as unknown as Record<string, unknown>)[name] = props[name as keyof typeof props];`,
    "});",
    ...expose,
    "onUnmounted(() => {",
    ...target.events.map((event, index) =>
      `  root.value?.removeEventListener(${quote(event.name)}, eventListener${index});`
    ),
    "  detach?.();",
    "});",
    "</script>",
    "",
    `<template>`,
    ...(isVoidElement(template.name) && !polymorphic
      ? [`  <${template.name} v-bind="$attrs"${rootAttributes.length === 0 ? "" : ` ${rootAttributes.join(" ")}`}>`]
      : [
        `  <${polymorphic ? `component :is="props.as ?? '${template.name}'"` : template.name} v-bind="$attrs"${rootAttributes.length === 0 ? "" : ` ${rootAttributes.join(" ")}`}>`,
        children === "" ? "" : `    ${children}`,
        `  </${polymorphic ? "component" : template.name}>`,
      ]),
    `</template>`,
    "",
  ].filter((line, index, all) => line !== "" || all[index - 1] !== "").join("\n");
}
