import type { ComponentDefinition } from "../template.js";
import type { PropContract, PropType } from "../types.js";

function typeSource(type: PropType): string {
  return typeof type === "object" ? type.enum.map((value) => `\`${value}\``).join(" \\| ") : `\`${type}\``;
}

function defaultSource(prop: PropContract): string {
  return "default" in prop ? `\`${JSON.stringify(prop.default)}\`` : "—";
}

function targetSource(prop: PropContract): string {
  return "attribute" in prop.target
    ? `attribute \`${prop.target.attribute}\``
    : `property \`${prop.target.property}\``;
}

function cell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll(/\s+/g, " ").trim();
}

export function generateDocs(definition: ComponentDefinition, version: string): string {
  const { contract } = definition;
  const props = Object.entries(contract.props);
  const rows = props.length === 0
    ? ["| — | — | — | — | — | This component has no declared props. |"]
    : props.map(([name, prop]) =>
      `| \`${name}\` | ${typeSource(prop.type)} | ${prop.required ? "yes" : "no"} | ${defaultSource(prop)} | ${targetSource(prop)} | ${cell(prop.description)} |`,
    );

  return [
    `<!-- Generated by HTML Next ${version}. Do not edit. -->`,
    `# ${contract.name}`,
    "",
    `> **Status: ${contract.status.toUpperCase()}** — HTML Next early-release component API.`,
    "",
    contract.summary,
    "",
    `- Invocation: \`<${contract.tag}>\``,
    `- Native element: \`<${contract.nativeElement}>\``,
    `- Contract schema: \`${contract.version}\``,
    "",
    "## Props",
    "",
    "| Prop | Type | Required | Default | Target | Description |",
    "| --- | --- | --- | --- | --- | --- |",
    ...rows,
    "",
    "Native attributes and framework-native event surfaces pass through to the native root. Declared prop targets and template-owned attributes take precedence.",
    "",
    "## Usage",
    "",
    "```html",
    `<${contract.tag}>Button label</${contract.tag}>`,
    "```",
    "",
    "```tsx",
    `import { ${contract.name} } from "./react/${contract.name}.js";`,
    "",
    `<${contract.name}>Button label</${contract.name}>`,
    "```",
    "",
    "## Coming soon",
    "",
    "State, computed values, data sources, control flow, filters, and actions are Coming soon. Named slots, component composition, reactive browser updates, SSR, and hydration are also Coming soon.",
    "",
  ].join("\n");
}
