import type { ComponentDefinition, TemplateNode } from "../template.js";
import type { PropContract, PropType } from "../types.js";

const REACT_NATIVE_TYPES: Readonly<Record<string, string>> = {
  a: "AnchorHTMLAttributes",
  button: "ButtonHTMLAttributes",
  form: "FormHTMLAttributes",
  img: "ImgHTMLAttributes",
  input: "InputHTMLAttributes",
  label: "LabelHTMLAttributes",
  output: "OutputHTMLAttributes",
  select: "SelectHTMLAttributes",
  textarea: "TextareaHTMLAttributes",
};

const REACT_ELEMENT_TYPES: Readonly<Record<string, string>> = {
  a: "HTMLAnchorElement",
  button: "HTMLButtonElement",
  form: "HTMLFormElement",
  img: "HTMLImageElement",
  input: "HTMLInputElement",
  label: "HTMLLabelElement",
  output: "HTMLOutputElement",
  select: "HTMLSelectElement",
  textarea: "HTMLTextAreaElement",
};

function quote(value: string): string {
  return JSON.stringify(value);
}

function propKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : quote(name);
}

function typeSource(type: PropType): string {
  return typeof type === "object" ? type.enum.map(quote).join(" | ") : type;
}

function htmlAttributeName(name: string): string {
  if (name === "class") return "className";
  if (name === "for") return "htmlFor";
  return name;
}

function textExpression(value: string): string {
  return `{${quote(value)}}`;
}

function renderNode(node: TemplateNode, aliases: ReadonlyMap<string, string>, depth: number): string {
  if (node.kind === "text") return textExpression(node.value);
  if (node.kind === "slot") return "{children}";
  const indent = "  ".repeat(depth);
  const attributes = node.attributes.map((attribute) => {
    if (attribute.kind === "literal") {
      return `${htmlAttributeName(attribute.name)}=${quote(attribute.value)}`;
    }
    return `${htmlAttributeName(attribute.name)}={${aliases.get(attribute.expression)!}}`;
  });
  const open = `<${node.name}${attributes.length === 0 ? "" : ` ${attributes.join(" ")}`}>`;
  if (node.children.length === 0) return `${open}</${node.name}>`;
  const children = node.children.map((child) => renderNode(child, aliases, depth + 1)).join("\n");
  return `${open}\n${indent}  ${children}\n${indent}</${node.name}>`;
}

export function generateReact(definition: ComponentDefinition, version: string): string {
  const { contract, template } = definition;
  const props = Object.entries(contract.props);
  const aliases = new Map(props.map(([name], index) => [name, `prop${index}`]));
  const nativeType = REACT_NATIVE_TYPES[contract.nativeElement] ?? "HTMLAttributes";
  const elementType = REACT_ELEMENT_TYPES[contract.nativeElement] ?? "HTMLElement";
  const imports = [...new Set([nativeType, "ReactNode", "Ref"])].sort().join(", ");
  const destructured = props.map(([name, prop], index) => {
    const defaultValue = "default" in prop ? ` = ${JSON.stringify(prop.default)}` : "";
    return `${quote(name)}: prop${index}${defaultValue}`;
  });
  const rootAttributes = [
    "{...nativeProps}",
    ...template.attributes.map((attribute) => {
      if (attribute.kind === "literal") return `${htmlAttributeName(attribute.name)}=${quote(attribute.value)}`;
      return `${htmlAttributeName(attribute.name)}={${aliases.get(attribute.expression)!}}`;
    }),
    "ref={ref}",
  ].join(" ");
  const children = template.children.map((child) => renderNode(child, aliases, 2)).join("\n");

  return [
    `// Generated by HTML7 ${version} for React 19. Do not edit.`,
    `import type { ${imports} } from "react";`,
    `import "../styles/${contract.tag}.css";`,
    "",
    `interface ${contract.name}OwnProps {`,
    ...props.map(([name, prop]) =>
      `  ${propKey(name)}${prop.required ? "" : "?"}: ${typeSource(prop.type)}${prop.required ? "" : " | null"};`,
    ),
    "}",
    "",
    `export type ${contract.name}Props = Omit<${nativeType}<${elementType}>, keyof ${contract.name}OwnProps | "children"> &`,
    `  ${contract.name}OwnProps & { children?: ReactNode; ref?: Ref<${elementType}> };`,
    "",
    `export function ${contract.name}(props: ${contract.name}Props) {`,
    `  const { ${[...destructured, "children", "ref", "...nativeProps"].join(", ")} } = props;`,
    "  return (",
    `    <${template.name} ${rootAttributes}>`,
    children === "" ? "" : `      ${children}`,
    `    </${template.name}>`,
    "  );",
    "}",
    "",
  ].filter((line, index, all) => line !== "" || all[index - 1] !== "").join("\n");
}
