import type { ComponentDefinition, TemplateNode } from "../template.js";
import type { PropContract } from "../types.js";
import {
  frameworkBindingExpression,
  propKey,
  quote,
  typeSource,
} from "./shared.js";

function htmlAttributeName(name: string): string {
  if (name === "class") return "className";
  if (name === "for") return "htmlFor";
  return name;
}

function textExpression(value: string): string {
  return `{${quote(value)}}`;
}

function renderNode(
  node: TemplateNode,
  aliases: ReadonlyMap<string, string>,
  props: Readonly<Record<string, PropContract>>,
  depth: number,
): string {
  if (node.kind === "text") return textExpression(node.value);
  if (node.kind === "slot") return "{children}";
  const indent = "  ".repeat(depth);
  const attributes = node.attributes.map((attribute) => {
    if (attribute.kind === "literal") {
      return `${htmlAttributeName(attribute.name)}=${quote(attribute.value)}`;
    }
    const value = aliases.get(attribute.expression)!;
    const expression = frameworkBindingExpression(
      attribute,
      props,
      node.name,
      value,
      '""',
    );
    return `${htmlAttributeName(attribute.name)}={${expression}}`;
  });
  const open = `<${node.name}${attributes.length === 0 ? "" : ` ${attributes.join(" ")}`}>`;
  if (node.children.length === 0) return `${open}</${node.name}>`;
  const children = node.children.map((child) => renderNode(child, aliases, props, depth + 1)).join("\n");
  return `${open}\n${indent}  ${children}\n${indent}</${node.name}>`;
}

export function generateReact(definition: ComponentDefinition, version: string): string {
  const { contract, template } = definition;
  const props = Object.entries(contract.props);
  const aliases = new Map(props.map(([name], index) => [name, `prop${index}`]));
  const nativeElement = quote(contract.nativeElement);
  const destructured = props.map(([name, prop], index) => {
    const defaultValue = "default" in prop ? ` = ${JSON.stringify(prop.default)}` : "";
    return `${quote(name)}: prop${index}${defaultValue}`;
  });
  const rootAttributes = [
    "{...nativeProps}",
    ...template.attributes.map((attribute) => {
      if (attribute.kind === "literal") return `${htmlAttributeName(attribute.name)}=${quote(attribute.value)}`;
      const value = aliases.get(attribute.expression)!;
      const expression = frameworkBindingExpression(
        attribute,
        contract.props,
        template.name,
        value,
        '""',
      );
      return `${htmlAttributeName(attribute.name)}={${expression}}`;
    }),
    "ref={ref}",
  ].join(" ");
  const children = template.children.map((child) => renderNode(child, aliases, contract.props, 2)).join("\n");

  return [
    `// Generated by HTML Next ${version} for React 19. Do not edit.`,
    'import type { ComponentPropsWithoutRef, ComponentRef, ReactNode, Ref } from "react";',
    `import "../styles/${contract.tag}.css";`,
    "",
    `interface ${contract.name}OwnProps {`,
    ...props.map(([name, prop]) =>
      `  ${propKey(name)}${prop.required ? "" : "?"}: ${typeSource(prop.type)}${prop.required ? "" : " | null"};`,
    ),
    "}",
    "",
    `export type ${contract.name}Props = Omit<ComponentPropsWithoutRef<${nativeElement}>, keyof ${contract.name}OwnProps | "children"> &`,
    `  ${contract.name}OwnProps & { children?: ReactNode; ref?: Ref<ComponentRef<${nativeElement}>> };`,
    "",
    `export function ${contract.name}(props: ${contract.name}Props) {`,
    `  const { ${[...destructured, "children", "ref", "...nativeProps"].join(", ")} } = props;`,
    "  return (",
    `    <${template.name} ${rootAttributes}>`,
    children === "" ? "" : `      ${children}`,
    `    </${template.name}>`,
    "  );",
    "}",
    "",
  ].filter((line, index, all) => line !== "" || all[index - 1] !== "").join("\n");
}
