import type { ComponentDefinition, TemplateNode } from "../template.js";
import type { PropType } from "../types.js";

const SVELTE_NATIVE_TYPES: Readonly<Record<string, string>> = {
  a: "HTMLAnchorAttributes",
  button: "HTMLButtonAttributes",
  form: "HTMLFormAttributes",
  img: "HTMLImgAttributes",
  input: "HTMLInputAttributes",
  label: "HTMLLabelAttributes",
  select: "HTMLSelectAttributes",
  textarea: "HTMLTextareaAttributes",
};

function quote(value: string): string {
  return JSON.stringify(value);
}

function html(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll('"', "&quot;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("{", "&#123;")
    .replaceAll("}", "&#125;");
}

function literalAttribute(value: string): string {
  return `"${html(value)}"`;
}

function propKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : quote(name);
}

function typeSource(type: PropType): string {
  return typeof type === "object" ? type.enum.map(quote).join(" | ") : type;
}

function renderNode(node: TemplateNode, aliases: ReadonlyMap<string, string>, depth: number): string {
  if (node.kind === "text") return html(node.value);
  if (node.kind === "slot") return "{@render children?.()}";
  const indent = "  ".repeat(depth);
  const attributes = node.attributes.map((attribute) => {
    if (attribute.kind === "literal") return `${attribute.name}=${literalAttribute(attribute.value)}`;
    return `${attribute.name}={${aliases.get(attribute.expression)!}}`;
  });
  const open = `<${node.name}${attributes.length === 0 ? "" : ` ${attributes.join(" ")}`}>`;
  const children = node.children.map((child) => renderNode(child, aliases, depth + 1)).join("\n");
  return children === "" ? `${open}</${node.name}>` : `${open}\n${indent}  ${children}\n${indent}</${node.name}>`;
}

export function generateSvelte(definition: ComponentDefinition, version: string): string {
  const { contract, template } = definition;
  const props = Object.entries(contract.props);
  const aliases = new Map(props.map(([name], index) => [name, `prop${index}`]));
  const nativeType = SVELTE_NATIVE_TYPES[contract.nativeElement] ?? "HTMLAttributes";
  const destructured = props.map(([name, prop], index) =>
    `${quote(name)}: prop${index}${"default" in prop ? ` = ${JSON.stringify(prop.default)}` : ""}`,
  );
  const rootAttributes = [
    "{...nativeProps}",
    ...template.attributes.map((attribute) => {
      if (attribute.kind === "literal") return `${attribute.name}=${literalAttribute(attribute.value)}`;
      return `${attribute.name}={${aliases.get(attribute.expression)!}}`;
    }),
  ];
  const children = template.children.map((child) => renderNode(child, aliases, 0)).join("\n");

  return [
    `<!-- Generated by HTML7 ${version} for Svelte 5. Do not edit. -->`,
    '<script lang="ts">',
    '  import type { Snippet } from "svelte";',
    `  import type { ${nativeType} } from "svelte/elements";`,
    `  import "../styles/${contract.tag}.css";`,
    "",
    `  interface OwnProps {`,
    ...props.map(([name, prop]) => `    ${propKey(name)}${prop.required ? "" : "?"}: ${typeSource(prop.type)}${prop.required ? "" : " | null"};`),
    "  }",
    `  type Props = Omit<${nativeType}, keyof OwnProps | "children"> & OwnProps & { children?: Snippet };`,
    "",
    `  let { ${[...destructured, "children", "...nativeProps"].join(", ")} }: Props = $props();`,
    "</script>",
    "",
    `<${template.name} ${rootAttributes.join(" ")}>`,
    children === "" ? "" : `  ${children}`,
    `</${template.name}>`,
    "",
  ].filter((line, index, all) => line !== "" || all[index - 1] !== "").join("\n");
}
