import type { ComponentDefinition, TemplateNode } from "../template.js";
import {
  escapeHtml,
  frameworkBindingExpression,
  literalAttribute,
  provenanceAttributes,
  propKey,
  quote,
  typeSource,
} from "./shared.js";

function renderNode(
  node: TemplateNode,
  aliases: ReadonlyMap<string, string>,
  definition: ComponentDefinition,
  depth: number,
): string {
  if (node.kind === "text") return escapeHtml(node.value);
  if (node.kind === "slot") return "{@render children?.()}";
  const indent = "  ".repeat(depth);
  const attributes = node.attributes.map((attribute) => {
    if (attribute.kind === "literal") return `${attribute.name}=${literalAttribute(attribute.value)}`;
    const value = aliases.get(attribute.expression)!;
    const expression = frameworkBindingExpression(
      attribute,
      definition.contract.props,
      node.name,
      value,
      '""',
    );
    return `${attribute.name}={${expression}}`;
  });
  attributes.push(...provenanceAttributes(definition.contract.tag));
  const open = `<${node.name}${attributes.length === 0 ? "" : ` ${attributes.join(" ")}`}>`;
  const children = node.children.map((child) => renderNode(child, aliases, definition, depth + 1)).join("\n");
  return children === "" ? `${open}</${node.name}>` : `${open}\n${indent}  ${children}\n${indent}</${node.name}>`;
}

export function generateSvelte(definition: ComponentDefinition, version: string): string {
  const { contract, template } = definition;
  const props = Object.entries(contract.props);
  const aliases = new Map(props.map(([name], index) => [name, `prop${index}`]));
  const nativeElement = quote(contract.nativeElement);
  const destructured = props.map(([name, prop], index) =>
    `${quote(name)}: prop${index}${"default" in prop ? ` = ${JSON.stringify(prop.default)}` : ""}`,
  );
  const rootAttributes = [
    "{...nativeProps}",
    ...provenanceAttributes(contract.tag, true),
    ...template.attributes.map((attribute) => {
      if (attribute.kind === "literal") return `${attribute.name}=${literalAttribute(attribute.value)}`;
      const value = aliases.get(attribute.expression)!;
      const expression = frameworkBindingExpression(
        attribute,
        contract.props,
        template.name,
        value,
        '""',
      );
      return `${attribute.name}={${expression}}`;
    }),
  ];
  const children = template.children.map((child) => renderNode(child, aliases, definition, 0)).join("\n");

  return [
    `<!-- Generated by HTML Next ${version} for Svelte 5. Do not edit. -->`,
    '<script lang="ts">',
    '  import type { Snippet } from "svelte";',
    '  import type { SvelteHTMLElements } from "svelte/elements";',
    `  import "../styles/${contract.tag}.css";`,
    "",
    `  interface OwnProps {`,
    ...props.map(([name, prop]) => `    ${propKey(name)}${prop.required ? "" : "?"}: ${typeSource(prop.type)}${prop.required ? "" : " | null"};`),
    "  }",
    `  type Props = Omit<SvelteHTMLElements[${nativeElement}], keyof OwnProps | "children"> & OwnProps & { children?: Snippet };`,
    "",
    `  let { ${[...destructured, "children", "...nativeProps"].join(", ")} }: Props = $props();`,
    "</script>",
    "",
    `<${template.name} ${rootAttributes.join(" ")}>`,
    children === "" ? "" : `  ${children}`,
    `</${template.name}>`,
    "",
  ].filter((line, index, all) => line !== "" || all[index - 1] !== "").join("\n");
}
