import type { ComponentDefinition, ElementNode, TemplateNode } from "../template.js";
import type { PropContract, PropType } from "../types.js";
import { getDomInterface } from "../platform.js";
import { typeScriptType } from "../type-system.js";

function js(value: string): string {
  return JSON.stringify(value);
}

function tsKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : js(name);
}

function tsType(type: PropType): string {
  return typeScriptType(type);
}

function optional(prop: PropContract): string {
  return prop.required ? "" : "?";
}

function nullable(prop: PropContract): string {
  return prop.required ? "" : " | null";
}

function renderNode(
  node: TemplateNode,
  lines: string[],
  counter: { value: number },
  parent: string,
  props: Readonly<Record<string, PropContract>>,
  valueCounter: { value: number },
  owner: string,
): void {
  if (node.kind === "text") {
    lines.push(`  ${parent}.append(${js(node.value)});`);
    return;
  }
  if (node.kind === "slot") {
    lines.push(`  for (const child of children) ${parent}.append(child);`);
    return;
  }

  const variable = `element${counter.value++}`;
  lines.push(`  const ${variable} = document.createElement(${js(node.name)});`);
  renderAttributes(node, variable, lines, props, valueCounter, "  ");
  lines.push(`  ${variable}.setAttribute("data-component", ${js(owner)});`);
  for (const child of node.children) renderNode(child, lines, counter, variable, props, valueCounter, owner);
  lines.push(`  ${parent}.append(${variable});`);
}

function renderAttributes(
  node: ElementNode,
  variable: string,
  lines: string[],
  props: Readonly<Record<string, PropContract>>,
  valueCounter: { value: number },
  indent: string,
): void {
  for (const attribute of node.attributes) {
    if (attribute.kind === "literal") {
      lines.push(`${indent}${variable}.setAttribute(${js(attribute.name)}, ${js(attribute.value)});`);
      continue;
    }
    const prop = props[attribute.expression]!;
    const expression = `componentProps[${js(attribute.expression)}] === undefined ? ${"default" in prop ? JSON.stringify(prop.default) : "undefined"} : componentProps[${js(attribute.expression)}]`;
    const local = `value${valueCounter.value++}`;
    lines.push(`${indent}const ${local} = ${expression};`);
    if (attribute.kind === "property") {
      lines.push(`${indent}if (${local} !== undefined) ${variable}[${js(attribute.name)}] = ${local};`);
    } else if (prop.type === "boolean") {
      lines.push(`${indent}if (${local} === true) ${variable}.setAttribute(${js(attribute.name)}, "");`);
      lines.push(`${indent}else ${variable}.removeAttribute(${js(attribute.name)});`);
    } else {
      lines.push(`${indent}if (${local} === null || ${local} === undefined) ${variable}.removeAttribute(${js(attribute.name)});`);
      lines.push(`${indent}else ${variable}.setAttribute(${js(attribute.name)}, String(${local}));`);
    }
  }
}

export function generateVanilla(
  definition: ComponentDefinition,
  version: string,
): { readonly module: string; readonly declaration: string } {
  const { contract, template } = definition;
  const props = Object.entries(contract.props);
  const hasRequired = props.some(([, prop]) => prop.required);
  const lines = [
    `// Generated by HTML Next ${version} for Vanilla DOM. Do not edit.`,
    `import "../styles/${contract.tag}.css";`,
    "",
    `export function create${contract.name}(options${hasRequired ? "" : " = {}"}) {`,
    "  const { attributes = {}, children = [], ...componentProps } = options;",
    `  const element = document.createElement(${js(template.name)});`,
    "  for (const [name, value] of Object.entries(attributes)) {",
    "    if (value === null || value === undefined || value === false) continue;",
    "    element.setAttribute(name, value === true ? \"\" : String(value));",
    "  }",
  ];
  const valueCounter = { value: 0 };
  renderAttributes(template, "element", lines, contract.props, valueCounter, "  ");
  lines.push(
    `  element.setAttribute("data-component", ${js(contract.tag)});`,
    `  element.setAttribute("data-component-root", ${js(contract.tag)});`,
  );
  const counter = { value: 0 };
  for (const child of template.children) {
    renderNode(child, lines, counter, "element", contract.props, valueCounter, contract.tag);
  }
  lines.push("  return element;", "}", "");

  const domType = getDomInterface(contract.nativeElement) ?? "HTMLElement";
  const declaration = [
    `// Generated by HTML Next ${version} for Vanilla DOM. Do not edit.`,
    `export interface ${contract.name}Props {`,
    ...props.map(
      ([name, prop]) => `  ${tsKey(name)}${optional(prop)}: ${tsType(prop.type)}${nullable(prop)};`,
    ),
    "  attributes?: Readonly<Record<string, string | number | boolean | null | undefined>>;",
    "  children?: readonly (string | Node)[];",
    "}",
    `export declare function create${contract.name}(props${hasRequired ? "" : "?"}: ${contract.name}Props): ${domType};`,
    "",
  ].join("\n");

  return { module: `${lines.join("\n")}\n`, declaration };
}
