import type { ComponentDefinition, TemplateNode } from "../template.js";
import {
  escapeHtml,
  frameworkBindingExpression,
  literalAttribute,
  provenanceAttributes,
  propKey,
  quote,
  typeSource,
} from "./shared.js";

function access(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? `props.${name}` : `props['${name}']`;
}

function renderNode(
  node: TemplateNode,
  definition: ComponentDefinition,
  depth: number,
): string {
  if (node.kind === "text") return escapeHtml(node.value);
  if (node.kind === "slot") return "<slot></slot>";
  const indent = "  ".repeat(depth);
  const attributes = node.attributes.map((attribute) => {
    if (attribute.kind === "literal") return `${attribute.name}=${literalAttribute(attribute.value)}`;
    const value = access(attribute.expression);
    const expression = frameworkBindingExpression(
      attribute,
      definition.contract.props,
      node.name,
      value,
      "''",
    );
    return `:${attribute.name}=${quote(expression)}`;
  });
  attributes.push(...provenanceAttributes(definition.contract.tag));
  const open = `<${node.name}${attributes.length === 0 ? "" : ` ${attributes.join(" ")}`}>`;
  const children = node.children.map((child) => renderNode(child, definition, depth + 1)).join("\n");
  return children === "" ? `${open}</${node.name}>` : `${open}\n${indent}  ${children}\n${indent}</${node.name}>`;
}

export function generateVue(definition: ComponentDefinition, version: string): string {
  const { contract, template } = definition;
  const props = Object.entries(contract.props);
  const defaults = props.filter(([, prop]) => "default" in prop);
  const define = [
    "defineProps<{",
    ...props.map(([name, prop]) => `  ${propKey(name)}${prop.required ? "" : "?"}: ${typeSource(prop.type)}${prop.required ? "" : " | null"};`),
    "}>()",
  ].join("\n");
  const declaration = defaults.length === 0
    ? `const props = ${define};`
    : `const props = withDefaults(${define}, {\n${defaults.map(([name, prop]) => `  ${propKey(name)}: ${JSON.stringify(prop.default)},`).join("\n")}\n});`;
  const rootAttributes = [...provenanceAttributes(contract.tag, true), ...template.attributes.map((attribute) => {
    if (attribute.kind === "literal") return `${attribute.name}=${literalAttribute(attribute.value)}`;
    const value = access(attribute.expression);
    const expression = frameworkBindingExpression(
      attribute,
      contract.props,
      template.name,
      value,
      "''",
    );
    return `:${attribute.name}=${quote(expression)}`;
  })];
  const children = template.children.map((child) => renderNode(child, definition, 1)).join("\n");

  return [
    `<!-- Generated by HTML Next ${version} for Vue 3.5. Do not edit. -->`,
    '<script setup lang="ts">',
    `import "../styles/${contract.tag}.css";`,
    "",
    "defineOptions({ inheritAttrs: false });",
    "",
    declaration,
    "</script>",
    "",
    `<template>`,
    `  <${template.name} v-bind="$attrs"${rootAttributes.length === 0 ? "" : ` ${rootAttributes.join(" ")}`}>`,
    children === "" ? "" : `    ${children}`,
    `  </${template.name}>`,
    `</template>`,
    "",
  ].filter((line, index, all) => line !== "" || all[index - 1] !== "").join("\n");
}
