import type { ComponentDefinition, TemplateNode } from "../template.js";
import type { PropType } from "../types.js";

function quote(value: string): string {
  return JSON.stringify(value);
}

function html(value: string): string {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll('"', "&quot;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll("{", "&#123;")
    .replaceAll("}", "&#125;");
}

function literalAttribute(value: string): string {
  return `"${html(value)}"`;
}

function propKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : quote(name);
}

function typeSource(type: PropType): string {
  return typeof type === "object" ? type.enum.map(quote).join(" | ") : type;
}

function access(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? `props.${name}` : `props['${name}']`;
}

function renderNode(node: TemplateNode, depth: number): string {
  if (node.kind === "text") return html(node.value);
  if (node.kind === "slot") return "<slot></slot>";
  const indent = "  ".repeat(depth);
  const attributes = node.attributes.map((attribute) => {
    if (attribute.kind === "literal") return `${attribute.name}=${literalAttribute(attribute.value)}`;
    return `:${attribute.name}=${quote(access(attribute.expression))}`;
  });
  const open = `<${node.name}${attributes.length === 0 ? "" : ` ${attributes.join(" ")}`}>`;
  const children = node.children.map((child) => renderNode(child, depth + 1)).join("\n");
  return children === "" ? `${open}</${node.name}>` : `${open}\n${indent}  ${children}\n${indent}</${node.name}>`;
}

export function generateVue(definition: ComponentDefinition, version: string): string {
  const { contract, template } = definition;
  const props = Object.entries(contract.props);
  const defaults = props.filter(([, prop]) => "default" in prop);
  const define = [
    "defineProps<{",
    ...props.map(([name, prop]) => `  ${propKey(name)}${prop.required ? "" : "?"}: ${typeSource(prop.type)}${prop.required ? "" : " | null"};`),
    "}>()",
  ].join("\n");
  const declaration = defaults.length === 0
    ? `const props = ${define};`
    : `const props = withDefaults(${define}, {\n${defaults.map(([name, prop]) => `  ${propKey(name)}: ${JSON.stringify(prop.default)},`).join("\n")}\n});`;
  const rootAttributes = template.attributes.map((attribute) => {
    if (attribute.kind === "literal") return `${attribute.name}=${literalAttribute(attribute.value)}`;
    return `:${attribute.name}=${quote(access(attribute.expression))}`;
  });
  const children = template.children.map((child) => renderNode(child, 1)).join("\n");

  return [
    `<!-- Generated by HTML7 ${version} for Vue 3.5. Do not edit. -->`,
    '<script setup lang="ts">',
    `import "../styles/${contract.tag}.css";`,
    "",
    "defineOptions({ inheritAttrs: false });",
    "",
    declaration,
    "</script>",
    "",
    `<template>`,
    `  <${template.name} v-bind="$attrs"${rootAttributes.length === 0 ? "" : ` ${rootAttributes.join(" ")}`}>`,
    children === "" ? "" : `    ${children}`,
    `  </${template.name}>`,
    `</template>`,
    "",
  ].filter((line, index, all) => line !== "" || all[index - 1] !== "").join("\n");
}
