import { execFile } from "node:child_process";
import { createHash } from "node:crypto";
import { lstat, mkdir, readFile, readdir, realpath, rm, stat, symlink, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, extname, isAbsolute, relative, resolve, sep } from "node:path";
import { promisify } from "node:util";
import { convertComponents, type FrameworkTarget } from "@nextwebwg/html-next-converter";
import ts from "typescript";
import type { Plugin, ViteDevServer } from "vite";

const run = promisify(execFile);
const require = createRequire(import.meta.url);
const header = "// Generated by HTML Next. Do not edit.\n";

export interface FrameworkPluginOptions {
  readonly target: FrameworkTarget;
  readonly root?: string;
  /** Local component resources to prepare before the first import or standalone typecheck. */
  readonly entries?: readonly string[];
  /** Generated ambient declarations; include this file in the consumer's TypeScript project. */
  readonly declarationsFile?: string;
  readonly publicRootURL?: string;
}

export interface FrameworkSyncResult {
  readonly aliases: ReadonlyMap<string, string>;
  readonly sourceFiles: readonly string[];
  readonly declarationsFile: string;
}

function slash(path: string): string { return path.split(sep).join("/"); }
function importPath(from: string, to: string): string {
  const path = slash(relative(dirname(from), to));
  return path.startsWith(".") ? path : `./${path}`;
}
function identity(path: string): string {
  return createHash("sha256").update(path).digest("hex").slice(0, 20);
}
async function exists(path: string): Promise<boolean> {
  return stat(path).then(() => true, (error: unknown) => {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return false;
    throw error;
  });
}
async function sourceFiles(directory: string): Promise<string[]> {
  const files: string[] = [];
  for (const item of await readdir(directory, { withFileTypes: true })) {
    if (["types", "node_modules"].includes(item.name)) continue;
    const path = resolve(directory, item.name);
    if (item.isDirectory()) files.push(...await sourceFiles(path));
    else if (/\.(?:vue|[cm]?[jt]sx?)$/.test(item.name)) files.push(path);
  }
  return files;
}

async function writeGenerated(path: string, content: string): Promise<void> {
  const previous = await readFile(path, "utf8").catch((error: unknown) => {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
    throw error;
  });
  if (previous === content) return;
  if (previous !== undefined && !previous.startsWith(header)) {
    throw new Error(`HTML Next will not overwrite an authored declaration: ${path}. Choose declarationsFile or remove the conflicting file.`);
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf8");
}

/** Only packages explicitly opting into the html-next export condition are converted. */
function sourceExports(exports: unknown): readonly [string, string][] {
  if (exports === null || typeof exports !== "object" || Array.isArray(exports)) return [];
  const record = exports as Record<string, unknown>;
  if (typeof record["html-next"] === "string") return [[".", record["html-next"]]];
  return Object.entries(record).flatMap(([subpath, value]) => {
    if (!subpath.startsWith(".") || subpath.includes("*")) return [];
    return sourceExports(value).map(([, source]) => [subpath, source] as [string, string]);
  });
}
async function packageDirectory(root: string, name: string): Promise<string | undefined> {
  let current = root;
  while (true) {
    const candidate = resolve(current, "node_modules", name);
    if (await exists(resolve(candidate, "package.json"))) return realpath(candidate);
    const parent = dirname(current);
    if (parent === current) return undefined;
    current = parent;
  }
}

class FrameworkCompiler {
  readonly aliases = new Map<string, string>();
  readonly sources = new Set<string>();
  readonly localSources = new Set<string>();
  readonly root: string;
  readonly declarationsFile: string;
  private readonly conversions = new Map<string, Promise<string>>();
  private readonly modules: string[] = [];
  private readonly locals = new Map<string, Promise<string>>();
  private readonly sourceModules = new Map<string, { content: string; imports: { start: number; end: number; source: string }[] }>();

  constructor(private readonly options: FrameworkPluginOptions) {
    this.root = resolve(options.root ?? process.cwd());
    this.declarationsFile = resolve(this.root, options.declarationsFile ?? "src/html-next.d.ts");
  }

  private async linkDependencies(cache: string, packageRoot: string): Promise<void> {
    const manifest = JSON.parse(await readFile(resolve(packageRoot, "package.json"), "utf8")) as {
      dependencies?: Record<string, string>; peerDependencies?: Record<string, string>;
    };
    const names = new Set([...Object.keys(manifest.dependencies ?? {}), ...Object.keys(manifest.peerDependencies ?? {})]);
    // $html's generated helper imports parse5; the adapter supplies it without an extra app install.
    names.add("parse5");
    for (const name of names) {
      const target = name === "parse5" ? await packageDirectory(dirname(require.resolve("parse5")), name)
        : await packageDirectory(packageRoot, name);
      if (target === undefined) continue;
      const link = resolve(cache, "node_modules", name);
      const previous = await lstat(link).catch((error: unknown) => {
        if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
        throw error;
      });
      if (previous !== undefined) {
        if (!previous.isSymbolicLink()) throw new Error(`Unexpected authored dependency in HTML Next cache: ${link}.`);
        if (await realpath(link).catch(() => "") === target) continue;
        await rm(link, { force: true });
      }
      await mkdir(dirname(link), { recursive: true });
      await symlink(target, link, process.platform === "win32" ? "junction" : "dir");
    }
  }

  async resource(source: string, packageRoot: string, cache: string): Promise<string> {
    const key = `${cache}:${source}`;
    const known = this.conversions.get(key);
    if (known !== undefined) return known;
    const conversion = this.convertResource(source, packageRoot, cache);
    this.conversions.set(key, conversion);
    return conversion;
  }
  private async convertResource(source: string, packageRoot: string, cache: string): Promise<string> {
    await this.linkDependencies(cache, packageRoot);
    const output = resolve(cache, "resources", identity(source));
    await rm(output, { recursive: true, force: true });
    const manifest = await convertComponents({ target: this.options.target, mode: "library", root: packageRoot,
      entries: [source], outDirectory: output,
      ...(this.options.publicRootURL === undefined ? {} : { publicRootURL: this.options.publicRootURL }) });
    for (const path of manifest.sourceFiles) this.sources.add(resolve(packageRoot, path));
    return resolve(output, manifest.output.entry);
  }

  private async sourceModule(source: string, packageRoot: string) {
    const known = this.sourceModules.get(source);
    if (known !== undefined) return known;
    const fromRoot = relative(packageRoot, source);
    if (fromRoot === ".." || fromRoot.startsWith(`..${sep}`) || isAbsolute(fromRoot)) {
      throw new Error(`HTML Next source import escapes its package: ${source}. Use a declared package dependency.`);
    }
    this.sources.add(source);
    const content = await readFile(source, "utf8");
    const parsed = ts.createSourceFile(source, content, ts.ScriptTarget.Latest, true);
    const imports: { start: number; end: number; source: string }[] = [];
    for (const statement of parsed.statements) {
      const specifier = (ts.isExportDeclaration(statement) || ts.isImportDeclaration(statement)) ? statement.moduleSpecifier : undefined;
      if (specifier === undefined || !ts.isStringLiteral(specifier) || !specifier.text.startsWith(".")) continue;
      const candidate = resolve(dirname(source), specifier.text);
      const candidates = [candidate, `${candidate}.ts`, `${candidate}.js`, resolve(candidate, "index.ts"), resolve(candidate, "index.js")];
      let resolved: string | undefined;
      for (const path of candidates) {
        const metadata = await stat(path).catch((error: unknown) => {
          if ((error as NodeJS.ErrnoException).code === "ENOENT") return undefined;
          throw error;
        });
        if (metadata?.isFile()) { resolved = path; break; }
      }
      if (resolved === undefined) throw new Error(`Cannot resolve ${specifier.text} from ${source}.`);
      imports.push({ start: specifier.getStart(parsed), end: specifier.end, source: resolved });
    }
    const module = { content, imports };
    this.sourceModules.set(source, module);
    return module;
  }

  private async collectResources(source: string, packageRoot: string, html: Set<string>, visited: Set<string>): Promise<void> {
    const fromRoot = relative(packageRoot, source);
    if (fromRoot === ".." || fromRoot.startsWith(`..${sep}`) || isAbsolute(fromRoot)) {
      throw new Error(`HTML Next source import escapes its package: ${source}. Use a declared package dependency.`);
    }
    if (visited.has(source)) return;
    visited.add(source);
    if (extname(source) === ".html") { html.add(source); return; }
    const module = await this.sourceModule(source, packageRoot);
    for (const item of module.imports) {
      if (/\.(?:html|[cm]?[jt]s)$/.test(item.source)) await this.collectResources(item.source, packageRoot, html, visited);
    }
  }

  /** One package graph emits shared linked components once, even when several entry points export them. */
  private async packageResources(entries: readonly string[], packageRoot: string, cache: string): Promise<void> {
    const html = new Set<string>();
    const visited = new Set<string>();
    for (const entry of entries) await this.collectResources(entry, packageRoot, html, visited);
    if (html.size === 0) throw new Error(`HTML Next source package contains no component resources: ${packageRoot}.`);
    const output = resolve(cache, "resources");
    await rm(output, { recursive: true, force: true });
    const manifest = await convertComponents({ target: this.options.target, mode: "library", root: packageRoot,
      entries: [...html], outDirectory: output,
      ...(this.options.publicRootURL === undefined ? {} : { publicRootURL: this.options.publicRootURL }) });
    for (const path of manifest.sourceFiles) this.sources.add(resolve(packageRoot, path));
    await rm(resolve(cache, "resource-entries"), { recursive: true, force: true });
    const names = new Map(manifest.components.map((item) => [item.tag, item.name]));
    const entriesBySource = new Map<string, typeof manifest.entries[number][]>();
    for (const component of manifest.entries) {
      const source = resolve(packageRoot, component.source);
      const entries = entriesBySource.get(source) ?? [];
      entries.push(component);
      entriesBySource.set(source, entries);
    }
    for (const source of html) {
      const entry = resolve(cache, "resource-entries", `${identity(source)}.ts`);
      const exports = entriesBySource.get(source)!.map((component) => {
        const name = names.get(component.tag)!;
        return `export { default as ${name} } from ${JSON.stringify(importPath(entry, resolve(output, component.artifact)))};`;
      });
      await mkdir(dirname(entry), { recursive: true });
      await writeFile(entry, exports.join("\n") + "\n", "utf8");
      this.conversions.set(`${cache}:${source}`, Promise.resolve(entry));
    }
  }

  /** Preserve library-authored aliases and re-exports while replacing HTML imports with source modules. */
  private async barrel(source: string, packageRoot: string, cache: string, seen: Map<string, string>): Promise<string> {
    if (extname(source) === ".html") return this.resource(source, packageRoot, cache);
    const previous = seen.get(source);
    if (previous !== undefined) return previous;
    const output = resolve(cache, "barrels", `${identity(source)}${extname(source)}`);
    seen.set(source, output);
    const module = await this.sourceModule(source, packageRoot);
    let rewritten = module.content;
    for (const item of module.imports.toReversed()) {
      const converted = /\.(?:html|[cm]?[jt]s)$/.test(item.source)
        ? await this.barrel(item.source, packageRoot, cache, seen) : item.source;
      rewritten = rewritten.slice(0, item.start) + JSON.stringify(importPath(output, converted)) + rewritten.slice(item.end);
    }
    await mkdir(dirname(output), { recursive: true });
    await writeFile(output, rewritten, "utf8");
    return output;
  }

  private async declarations(entry: string, cache: string): Promise<string> {
    const output = resolve(cache, "types");
    const declarationEntry = resolve(output, relative(cache, entry)).replace(/\.[cm]?[jt]sx?$/, ".d.ts");
    const files = (await sourceFiles(cache)).sort();
    const digest = createHash("sha256").update(ts.version).update(this.options.target);
    for (const path of files) digest.update(path).update(await readFile(path));
    const consumerRequire = createRequire(resolve(this.root, "package.json"));
    for (const name of [this.options.target, ...(this.options.target === "react" ? ["@types/react"] : [])]) {
      digest.update(await readFile(consumerRequire.resolve(`${name}/package.json`)));
    }
    if (this.options.target === "vue") digest.update(await readFile(require.resolve("vue-tsc/package.json")));
    const fingerprint = digest.digest("hex");
    const metadata = resolve(cache, "declarations.fingerprint");
    if (await readFile(metadata, "utf8").catch(() => "") === fingerprint && await exists(declarationEntry)) return declarationEntry;
    // Clear old declarations so removed exports cannot survive a rebuild.
    await rm(output, { recursive: true, force: true });
    const config = resolve(cache, "tsconfig.json");
    await writeFile(config, JSON.stringify({ compilerOptions: {
      target: "ES2022", module: "ESNext", moduleResolution: "Bundler", jsx: "react-jsx",
      strict: true, skipLibCheck: true, allowJs: true, checkJs: false, allowImportingTsExtensions: true,
      declaration: true, emitDeclarationOnly: true, noEmitOnError: true,
      rootDir: cache, outDir: output, types: [],
    }, files }), "utf8");
    const binary = this.options.target === "vue" ? require.resolve("vue-tsc/bin/vue-tsc.js") : require.resolve("typescript/bin/tsc");
    try { await run(process.execPath, [binary, "-p", config], { maxBuffer: 8 * 1024 * 1024 }); }
    catch (error) {
      const result = error as { stdout?: string; stderr?: string };
      throw new Error(`HTML Next ${this.options.target} declaration generation failed:\n${result.stdout ?? ""}${result.stderr ?? ""}`, { cause: error });
    }
    await writeFile(metadata, fingerprint, "utf8");
    return declarationEntry;
  }

  private async moduleDeclaration(specifier: string, entry: string, cache: string): Promise<void> {
    const declaration = await this.declarations(entry, cache);
    const program = ts.createProgram([declaration], { skipLibCheck: true, moduleResolution: ts.ModuleResolutionKind.Bundler, module: ts.ModuleKind.ESNext });
    const checker = program.getTypeChecker();
    const source = program.getSourceFile(declaration)!;
    const symbol = checker.getSymbolAtLocation(source);
    if (symbol === undefined) throw new Error(`No component exports were generated for ${specifier}.`);
    const exports = checker.getExportsOfModule(symbol);
    const path = JSON.stringify(importPath(this.declarationsFile, declaration).replace(/\.d\.ts$/, ""));
    this.modules.push(`declare module ${JSON.stringify(specifier)} {\n${exports.map((item) => {
      const target = item.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(item) : item;
      if (item.name === "default") return `  const component: typeof import(${path}).default;\n  export default component;`;
      if (target.flags & ts.SymbolFlags.Value) return `  export const ${item.name}: typeof import(${path}).${item.name};`;
      const declaration = target.declarations?.find((node) => ts.isInterfaceDeclaration(node) || ts.isTypeAliasDeclaration(node));
      const parameters = declaration !== undefined && (ts.isInterfaceDeclaration(declaration) || ts.isTypeAliasDeclaration(declaration))
        ? declaration.typeParameters ?? [] : [];
      const parameterSource = parameters.length === 0 ? "" : `<${parameters.map((parameter) => {
        const type = (node: ts.TypeNode) => checker.typeToString(checker.getTypeAtLocation(node), undefined, ts.TypeFormatFlags.UseFullyQualifiedType);
        return parameter.name.text + (parameter.constraint === undefined ? "" : ` extends ${type(parameter.constraint)}`)
          + (parameter.default === undefined ? "" : ` = ${type(parameter.default)}`);
      }).join(", ")}>`;
      const argumentsSource = parameters.length === 0 ? "" : `<${parameters.map((parameter) => parameter.name.text).join(", ")}>`;
      return `  export type ${item.name}${parameterSource} = import(${path}).${item.name}${argumentsSource};`;
    }).join("\n")}\n}`);
  }

  async prepare(): Promise<FrameworkSyncResult> {
    this.sources.add(resolve(this.root, "package.json"));
    const manifest = JSON.parse(await readFile(resolve(this.root, "package.json"), "utf8")) as {
      dependencies?: Record<string, string>; devDependencies?: Record<string, string>;
    };
    for (const name of new Set([...Object.keys(manifest.dependencies ?? {}), ...Object.keys(manifest.devDependencies ?? {})])) {
      const directory = await packageDirectory(this.root, name);
      if (directory === undefined) continue;
      const packageJSON = resolve(directory, "package.json");
      const definition = JSON.parse(await readFile(packageJSON, "utf8")) as { exports?: unknown };
      const exports = sourceExports(definition.exports);
      if (exports.length === 0) continue;
      this.sources.add(packageJSON);
      const cache = resolve(this.root, "node_modules", ".html-next", this.options.target, identity(directory));
      const paths = exports.map(([subpath, path]) => {
        if (!path.startsWith("./")) throw new Error(`HTML Next package exports must be relative: ${name} ${path}.`);
        const source = resolve(directory, path);
        if (!source.startsWith(`${directory}${sep}`)) throw new Error(`HTML Next export escapes ${name}: ${path}.`);
        return { specifier: subpath === "." ? name : `${name}/${subpath.slice(2)}`, source };
      });
      await this.linkDependencies(cache, directory);
      await this.packageResources(paths.map((item) => item.source), directory, cache);
      await rm(resolve(cache, "barrels"), { recursive: true, force: true });
      const seen = new Map<string, string>();
      for (const { specifier, source } of paths) this.aliases.set(specifier, await this.barrel(source, directory, cache, seen));
      for (const { specifier } of paths) await this.moduleDeclaration(specifier, this.aliases.get(specifier)!, cache);
    }
    for (const input of this.options.entries ?? []) await this.localResource(resolve(this.root, input));
    await writeGenerated(this.declarationsFile, header + this.modules.join("\n\n") + "\n");
    return { aliases: this.aliases, sourceFiles: [...this.sources], declarationsFile: this.declarationsFile };
  }

  localResource(source: string): Promise<string> {
    this.localSources.add(source);
    let result = this.locals.get(source);
    if (result === undefined) {
      result = this.convertLocalResource(source);
      this.locals.set(source, result);
    }
    return result;
  }

  private async convertLocalResource(source: string): Promise<string> {
    const cache = resolve(this.root, "node_modules", ".html-next", this.options.target, identity(source));
    const entry = await this.resource(source, this.root, cache);
    const declaration = await this.declarations(entry, cache);
    const sidecar = source.replace(/\.html$/, ".d.html.ts");
    await writeGenerated(sidecar, `${header}export * from ${JSON.stringify(importPath(sidecar, declaration).replace(/\.d\.ts$/, ""))};\n`);
    return entry;
  }
}

/** Prepare generated framework sources and types before an editor or standalone typechecker runs. */
export async function syncHtmlNext(options: FrameworkPluginOptions): Promise<FrameworkSyncResult> {
  return new FrameworkCompiler({ ...options, root: await realpath(resolve(options.root ?? process.cwd())) }).prepare();
}

export function frameworkVitePlugin(options: FrameworkPluginOptions): Plugin {
  let compiler: FrameworkCompiler;
  let current: FrameworkSyncResult;
  let server: ViteDevServer | undefined;
  let updates: Promise<void> = Promise.resolve();
  const initialize = async (root: string) => {
    compiler = new FrameworkCompiler({ ...options, root: await realpath(resolve(options.root ?? root)) });
    current = await compiler.prepare();
  };
  return {
    name: "html-next-framework",
    enforce: "pre",
    async config(config) {
      await initialize(resolve(config.root ?? process.cwd()));
      return { optimizeDeps: { exclude: [...current.aliases.keys()] }, resolve: { conditions: ["html-next", ...(config.resolve?.conditions ?? ["module", "browser", "development|production"])] } };
    },
    buildStart() { for (const path of current.sourceFiles) this.addWatchFile(path); },
    configureServer(value) { server = value; server.watcher.add(current.sourceFiles); },
    async resolveId(id, importer, resolveOptions) {
      // Requests can arrive between rapid source edits; wait until the current graph is complete.
      await updates;
      const alias = current.aliases.get(id);
      if (alias !== undefined) return alias;
      if (!id.endsWith(".html") || id.includes("?")) return null;
      const resolved = await this.resolve(id, importer, { ...resolveOptions, skipSelf: true });
      if (resolved === null || !isAbsolute(resolved.id)) return null;
      const entry = await compiler.localResource(resolved.id);
      for (const source of compiler.sources) this.addWatchFile(source);
      server?.watcher.add([...compiler.sources]);
      return entry;
    },
    async closeBundle() { await updates; },
    async handleHotUpdate(context) {
      const changed = await realpath(context.file).catch(() => context.file);
      if (!compiler.sources.has(changed) && !compiler.sources.has(context.file)) return;
      const update = updates.then(async () => {
        const locals = [...compiler.localSources];
        await initialize(server?.config.root ?? compiler.root);
        for (const path of locals) {
          if (await exists(path)) await compiler.localResource(path);
          else {
            const sidecar = path.replace(/\.html$/, ".d.html.ts");
            if ((await readFile(sidecar, "utf8").catch(() => "")).startsWith(header)) await rm(sidecar, { force: true });
          }
        }
        server?.watcher.add([...compiler.sources]);
        // A resource may export several components and types; invalidate their generated module graph together.
        for (const module of context.server.moduleGraph.idToModuleMap.values()) {
          if (module.id?.replaceAll("\\", "/").includes("/.html-next/")) context.server.moduleGraph.invalidateModule(module);
        }
        context.server.ws.send({ type: "full-reload" });
      });
      updates = update.catch(() => {});
      await update;
      return [];
    },
  };
}
