import { generateDocs } from "./targets/docs.js";
import { generateVanilla } from "./targets/vanilla.js";
import { generateVue } from "./targets/vue.js";
import type { ComponentDefinition } from "./template.js";
import { compileComponentStylesForBuild } from "./component-styles-build.js";

export const GENERATOR_VERSION = "1.0.0-alpha.0";

export interface GeneratedArtifact {
  readonly path: string;
  readonly content: string;
}

export function generateComponent(
  definition: ComponentDefinition,
): readonly GeneratedArtifact[] {
  const vanilla = generateVanilla(definition, GENERATOR_VERSION);
  const vue = generateVue(definition, GENERATOR_VERSION);
  const docs = generateDocs(definition, GENERATOR_VERSION);
  const { name, tag } = definition.contract;

  return Object.freeze([
    Object.freeze({ path: `vanilla/${name}.js`, content: vanilla.module }),
    Object.freeze({ path: `vanilla/${name}.d.ts`, content: vanilla.declaration }),
    Object.freeze({ path: `vue/${name}.vue`, content: vue }),
    Object.freeze({
      path: `styles/${tag}.css`,
      content: `/* Generated by HTML Next ${GENERATOR_VERSION}. Do not edit. */\n${compileComponentStylesForBuild(definition.css, definition).css}${definition.css === "" ? "" : "\n"}`,
    }),
    Object.freeze({ path: `docs/${tag}.md`, content: docs }),
  ]);
}

export type { ComponentDefinition } from "./template.js";
